In [1]:
import numpy as np
import pandas as pd
import re
import geopandas as gpd
from haversine import haversine, Unit

# 1. 바나프레소 정보만 가져오기

1. 서울 카페 정보 중 **바나프레소** 인 것만 필터링.
2. apv_date가 3년 전 이상인 것만 필터링 why? 3년 이상 영업 가게를 성공 가게라고 판단했기 때문.

In [2]:
# 카페 데이터 가져오기
cafe = pd.read_csv("C:/vs_code_prj/brewmap/data/mj/cafe.csv")
cafe.head()

,nm,type,apv_date,addr,floor,sitearea,lat,lng,flpop_type,trdar_cd,adstrd_cd
0,베레베레,커피숍,2002-09-19,서울 광진구 능동로13길 19,NaN,NaN,37.542885,127.070832,TR,3120053.0,11215710
1,덕수궁전통차전문,커피숍,2003-01-16,서울 중구 서소문로 109,2.0,46.28,37.563062,126.973280,TR,3120020.0,11140520
2,엘빠소,커피숍,2003-05-31,서울 종로구 성균관로 18,NaN,NaN,37.584406,126.997641,TR,3110021.0,11110650
3,씨애틀즈베스트커피대사관점,커피숍,2003-10-31,서울 종로구 세종대로 188,1.0,NaN,37.573190,126.977831,AD,NaN,11110615
4,본솔카페,커피숍,2004-01-17,서울 용산구 청파로47길 71,1.0,13.80,37.544840,126.966455,TR,3110069.0,11170555

In [3]:
# 바나프레소만 추출
bana_df = cafe[cafe['nm'].str.contains("바나프레소", na=False)].copy()
print(len(bana_df))

# 날짜 변환
bana_df['apv_date'] = pd.to_datetime(bana_df['apv_date'], errors='coerce')

# 오늘 기준 3년 이상(= 3년 전 이하) 된 매장만
cutoff = pd.Timestamp.today().normalize() - pd.DateOffset(years=3)
bana_df["success"] = (bana_df["apv_date"] <= cutoff).astype(int)

# 확인
bana_df["success"].value_counts()

58

success
0    48
1    10
Name: count, dtype: int64

# 2. 수요 점수 변수
2024년 4분기부터 2025년 3분기 까지의 데이터 사용 
<br>
- 2-1. 유동 인구_점심: tmzon_11_14_flpop_co
- 2-2. 유동 인구_저녁: tmzon_17_21_flpop_co
- 2-3. 유동 인구_기타 시간 평균: tmzon_00_06_flpop_co, tmzon_06_11_flpop_co, tmzon_14_17_flpop_co, tmzon_21_24_flpop_co

In [4]:
print(bana_df["flpop_type"].unique())

<StringArray>
['TR', 'AD', 'AL']
Length: 3, dtype: str

- 성공한 카페는 flpop_t.csv 만으로도 유동인구 값 가져올 수 있음

In [71]:
# 유동인구 데이터 불러오기
flpop_t = pd.read_csv("C:/vs_code_prj/brewmap/data/mj/flpop_t.csv")
print(flpop_t.columns)

Index(['stdr_yyqu_cd', 'trdar_se_cd_nm', 'trdar_cd', 'trdar_cd_nm',
       'tot_flpop_co', 'ml_flpop_co', 'fml_flpop_co', 'agrde_10_flpop_co',
       'agrde_20_flpop_co', 'agrde_30_flpop_co', 'agrde_40_flpop_co',
       'agrde_50_flpop_co', 'agrde_60_above_flpop_co', 'tmzon_00_06_flpop_co',
       'tmzon_06_11_flpop_co', 'tmzon_11_14_flpop_co', 'tmzon_14_17_flpop_co',
       'tmzon_17_21_flpop_co', 'tmzon_21_24_flpop_co', 'mon_flpop_co',
       'tues_flpop_co', 'wed_flpop_co', 'thur_flpop_co', 'fri_flpop_co',
       'sat_flpop_co', 'sun_flpop_co'],
      dtype='str')

In [72]:
# 최근 4개 분기 추출
recent_quarters = sorted(flpop_t["stdr_yyqu_cd"].unique())[-4:]

# 필터링
flpop_t = flpop_t[flpop_t["stdr_yyqu_cd"].isin(recent_quarters)]

In [73]:
# 중복(이상치) 확인
print(flpop_t[["stdr_yyqu_cd","trdar_cd"]].duplicated().sum())

0

In [77]:
# 분기 평균 집계
agg_cols = ["tmzon_11_14_flpop_co", "tmzon_17_21_flpop_co",
            "tmzon_00_06_flpop_co", "tmzon_06_11_flpop_co",
            "tmzon_14_17_flpop_co", "tmzon_21_24_flpop_co"]

flpop_t_agg = flpop_t.groupby("trdar_cd")[agg_cols].mean().reset_index()

# etc 평균 계산
etc_cols = ["tmzon_00_06_flpop_co", "tmzon_06_11_flpop_co", "tmzon_14_17_flpop_co", "tmzon_21_24_flpop_co"]
flpop_t_agg["flpop_etc"] = flpop_t_agg[etc_cols].mean(axis=1)
flpop_t_agg

,trdar_cd,tmzon_11_14_flpop_co,tmzon_17_21_flpop_co,tmzon_00_06_flpop_co,tmzon_06_11_flpop_co,tmzon_14_17_flpop_co,tmzon_21_24_flpop_co,flpop_etc
0,3001491,281088.25,402597.75,476771.75,357248.25,301798.00,273183.50,3.522504e+05
1,3001492,1766225.75,1358691.50,390051.50,1505678.50,1747818.50,357227.50,1.000194e+06
2,3001493,536464.00,654693.50,592612.50,670068.50,541661.00,403672.75,5.520037e+05
3,3001494,1734407.75,1660630.75,911272.25,1655835.25,1760761.75,671573.25,1.249861e+06
4,3001495,615172.50,891170.00,717608.50,738374.00,651910.50,483972.00,6.479662e+05
...,...,...,...,...,...,...,...,...
1645,3130323,32996.25,49594.00,84503.75,60058.00,33634.00,38989.75,5.429638e+04
1646,3130324,54661.50,76998.50,159406.00,107335.75,51321.00,73059.75,9.778062e+04
1647,3130325,41724.00,64311.50,61783.00,60552.50,42442.75,39066.75,5.096125e+04
1648,3130326,11467.50,17532.00,21130.50,21020.75,11652.00,11918.25,1.643038e+04
1649,3130327,8633.50,8936.50,12895.00,11549.75,8090.25,7445.00,9.995000e+03

In [90]:
# TR 매핑
bana_old_df = bana_old_df.merge(
    flpop_t_agg[["trdar_cd", "tmzon_11_14_flpop_co", "tmzon_17_21_flpop_co", "flpop_etc"]],
    on="trdar_cd", how="left"
).rename(columns={
    "tmzon_11_14_flpop_co": "flpop_lunch",
    "tmzon_17_21_flpop_co": "flpop_dinner"
})

bana_old_df

,nm,type,apv_date,addr,floor,sitearea,lat,lng,flpop_type,trdar_cd,adstrd_cd,detail,flpop_lunch,flpop_dinner,flpop_etc
0,바나프레소 테헤란로점,커피숍,2019-05-23,서울 강남구 테헤란로 208,1.0,98.40,37.501130,127.039099,TR,3120197.0,11680650,banapresso,985131.50,882135.00,752222.8125
1,바나프레소 신논현역점,커피숍,2019-08-06,서울 서초구 사평대로 364,1.0,107.24,37.503733,127.023196,TR,3120187.0,11650531,banapresso,589152.00,788268.00,560948.1250
2,바나프레소 선릉공원점,커피숍,2021-07-23,서울 강남구 테헤란로63길 20,1.0,97.28,37.506522,127.050398,TR,3120210.0,11680590,banapresso,951358.25,983513.00,833761.1250
3,바나프레소 충무로점,커피숍,2022-09-19,서울 중구 필동로 15,1.0,148.43,37.560339,126.996257,TR,3120032.0,11140570,banapresso,357098.25,362848.50,287171.8750
4,바나프레소 홍대입구역사거리점,커피숍,2022-11-07,서울 마포구 양화로 129,1.0,33.00,37.555061,126.920694,TR,3120102.0,11440660,banapresso,409679.75,552486.25,389756.6250
5,바나프레소 양재이안점,커피숍,2023-01-31,서울 서초구 강남대로34길 7,1.0,48.33,37.483032,127.036465,TR,3120179.0,11650651,banapresso,440356.25,473092.50,400709.2500
6,바나프레소 여의도파크원점,커피숍,2021-03-18,서울 영등포구 여의대로 108,-1.0,59.16,37.525191,126.929113,TR,3120149.0,11560540,banapresso,364928.50,317197.25,246954.3125
7,바나프레소 양평역점,커피숍,2015-08-05,서울 영등포구 양산로 43,1.0,59.40,37.525761,126.887942,TR,3120135.0,11560610,banapresso,82196.00,68874.00,71096.8750
8,바나프레소 명동중앙우체국점,커피숍,2021-10-29,서울 중구 명동8나길 51,1.0,193.85,37.561080,126.982077,TR,3120028.0,11140550,banapresso,449272.25,410975.75,273562.8125
9,바나프레소 마포역점,커피숍,2015-11-17,서울 마포구 마포대로 34,1.0,33.00,37.539260,126.946152,TR,3120106.0,11440585,banapresso,117808.75,141110.00,142316.5000

In [80]:
len(bana_old_df)

10

    2-4. 학교 수
    2-5. 지식산업센터 수
    2-6. 병원 수 
    2-7. 학원 수
    2-8. 체육도장업 수

In [28]:
academy = pd.read_csv("C:/vs_code_prj/brewmap/data/sa/seoul_data/academy_df.csv")
gym = pd.read_csv("C:/vs_code_prj/brewmap/data/sa/seoul_data/gym_df.csv")
hospital = pd.read_csv("C:/vs_code_prj/brewmap/data/sa/seoul_data/hospital_df.csv")
physical = pd.read_csv("C:/vs_code_prj/brewmap/data/sa/seoul_data/physical_df.csv")
school = pd.read_csv("C:/vs_code_prj/brewmap/data/sa/seoul_data/school.csv")
center = pd.read_csv("C:/vs_code_prj/brewmap/data/mj/industry_center.csv")
print(academy.columns)
print(gym.columns)
print(hospital.columns)
print(physical.columns)
print(school.columns)
print(center.columns)

Index(['idx', 'nm', 'addr', 'lat', 'lng'], dtype='str')
Index(['idx', 'dtlstatenm', 'addr', 'nm', 'type', 'lat', 'lng'], dtype='str')
Index(['idx', 'dtlstatenm', 'nm', 'type', 'addr', 'lat', 'lng'], dtype='str')
Index(['idx', 'dtlstatenm', 'addr', 'type', 'nm', 'lat', 'lng'], dtype='str')
Index(['idx', 'nm', 'addr', 'type', 'lat', 'lng'], dtype='str')
Index(['nm', 'type', 'addr', 'lat', 'lng'], dtype='str')

In [30]:
# academy 에 type 칼럼이 없어서 추가
academy['type'] = '학원'
academy.head()

   idx             nm                        addr        lat         lng type
0    1       클릭전원미술학원    서울특별시 마포구 와우산로 138 (창전동)  37.553572  126.928993   학원
1    2       고려직업전문학교   서울특별시 동작구 노량진로 186 (노량진동)  37.512575  126.946031   학원
2    3      노량진행정고시학원   서울특별시 동작구 노량진로 171 (노량진동)  37.514034  126.945198   학원
3    4      박문각임용고시학원   서울특별시 동작구 노량진로 171 (노량진동)  37.514034  126.945198   학원
4    5  노량진메가스터디입시어학원  서울특별시 동작구 장승배기로 171 (노량진동)  37.513017  126.939945   학원

In [31]:
# 하나의 데이터프레임으로 만들기
dfs = [academy, gym, hospital, physical, school, center]

need_cols = ["type", "nm", "addr", "lat", "lng"]

# 각 df에서 필요한 컬럼만 추출(없는 컬럼은 NaN으로 생성)
picked = [d.reindex(columns=need_cols) for d in dfs]

# 세로로 합치기
buildings_df = pd.concat(picked, ignore_index=True)

buildings_df.head()

  type             nm                        addr        lat         lng
0   학원       클릭전원미술학원    서울특별시 마포구 와우산로 138 (창전동)  37.553572  126.928993
1   학원       고려직업전문학교   서울특별시 동작구 노량진로 186 (노량진동)  37.512575  126.946031
2   학원      노량진행정고시학원   서울특별시 동작구 노량진로 171 (노량진동)  37.514034  126.945198
3   학원      박문각임용고시학원   서울특별시 동작구 노량진로 171 (노량진동)  37.514034  126.945198
4   학원  노량진메가스터디입시어학원  서울특별시 동작구 장승배기로 171 (노량진동)  37.513017  126.939945

In [36]:
buildings_df['type'].unique()

<StringArray>
['학원', '병원', '학교', '지식산업센터']
Length: 4, dtype: str

In [46]:
test.columns

Index(['nm', 'type', 'apv_date', 'addr', 'floor', 'sitearea', 'lat', 'lng',
       'flpop_type', 'trdar_cd', 'adstrd_cd', 'flpop_lunch', 'flpop_dinner',
       'flpop_etc', '병원', '지식산업센터', '학원'],
      dtype='str')

In [91]:
# 반경 300m 안 개수 찾기

# 0) type 매핑
type_map = {
    "학원": "cnt_academy",
    "병원": "cnt_hospital",
    "학교": "cnt_school",
    "지식산업센터": "cnt_company"
}

# 1) 함수 정의
def count_buildings_nearby(cafe_lat, cafe_lon, buildings_df, radius=300):
    mask = buildings_df.apply(
        lambda row: haversine(
            (cafe_lat, cafe_lon), (row["lat"], row["lng"]), unit=Unit.METERS
        ) <= radius, axis=1
    )
    nearby = buildings_df[mask]
    counts = nearby.groupby("type").size()
    
    # 없는 type도 0으로 채우기
    counts = counts.reindex(type_map.keys(), fill_value=0)
    
    # 영어로 rename
    counts.index = [type_map[t] for t in counts.index]
    return counts

# 적용
result = bana_old_df.apply(
    lambda row: count_buildings_nearby(row["lat"], row["lng"], buildings_df),
    axis=1
).fillna(0).astype(int)

bana_old_df = pd.concat([bana_old_df, result], axis=1)
bana_old_df.head()

,nm,type,apv_date,addr,floor,sitearea,lat,lng,flpop_type,trdar_cd,adstrd_cd,detail,flpop_lunch,flpop_dinner,flpop_etc,cnt_academy,cnt_hospital,cnt_school,cnt_company
0,바나프레소 테헤란로점,커피숍,2019-05-23,서울 강남구 테헤란로 208,1.0,98.40,37.501130,127.039099,TR,3120197.0,11680650,banapresso,985131.50,882135.00,752222.8125,0,1,0,0
1,바나프레소 신논현역점,커피숍,2019-08-06,서울 서초구 사평대로 364,1.0,107.24,37.503733,127.023196,TR,3120187.0,11650531,banapresso,589152.00,788268.00,560948.1250,0,1,0,0
2,바나프레소 선릉공원점,커피숍,2021-07-23,서울 강남구 테헤란로63길 20,1.0,97.28,37.506522,127.050398,TR,3120210.0,11680590,banapresso,951358.25,983513.00,833761.1250,1,2,0,0
3,바나프레소 충무로점,커피숍,2022-09-19,서울 중구 필동로 15,1.0,148.43,37.560339,126.996257,TR,3120032.0,11140570,banapresso,357098.25,362848.50,287171.8750,0,0,0,0
4,바나프레소 홍대입구역사거리점,커피숍,2022-11-07,서울 마포구 양화로 129,1.0,33.00,37.555061,126.920694,TR,3120102.0,11440660,banapresso,409679.75,552486.25,389756.6250,0,1,0,0

# 3. 접근성 점수 변수
    3-1. 지하철역 최소 거리
    3-2. 버스정류장 최소 거리
    3-3. 대로변 여부
    3-4. 횡단보도 수

In [49]:
bus_stop = pd.read_csv("C:/vs_code_prj/brewmap/data/dh/bus_stop.csv")
station = pd.read_csv("C:/vs_code_prj/brewmap/data/dh/station.csv")
crosswalk = pd.read_csv("C:/vs_code_prj/brewmap/data/dh/crosswalk.csv")
road = pd.read_csv("C:/vs_code_prj/brewmap/data/dh/road.csv")

print(bus_stop.columns)
print(station.columns)
print(crosswalk.columns)
print(road.columns)

Index(['bus_stop_id', 'bus_stop_nm', 'lng', 'lat', 'type'], dtype='str')
Index(['addr', 'type', 'lat', 'lng'], dtype='str')
Index(['lng', 'lat', 'sigungu', 'emd', 'type'], dtype='str')
Index(['road_address', 'lng', 'lat', 'type'], dtype='str')

In [92]:
# 최소 거리
def min_distance(cafe_lat, cafe_lon, df):
    distances = df.apply(
        lambda row: haversine(
            (cafe_lat, cafe_lon), (row["lat"], row["lng"]), unit=Unit.METERS
        ), axis=1
    )
    return distances.min()

# 300m 안 횡단보도 개수
def count_within(cafe_lat, cafe_lon, df, radius=300):
    mask = df.apply(
        lambda row: haversine(
            (cafe_lat, cafe_lon), (row["lat"], row["lng"]), unit=Unit.METERS
        ) <= radius, axis=1
    )
    return mask.sum()

# 300m 안 대로변 여부
def is_roadside(cafe_lat, cafe_lon, df, radius=300):
    mask = df.apply(
        lambda row: haversine(
            (cafe_lat, cafe_lon), (row["lat"], row["lng"]), unit=Unit.METERS
        ) <= radius, axis=1
    )
    return int(mask.any())  # 1개라도 있으면 1, 없으면 0

# bana_old_df에 적용
bana_old_df["dist_station"]    = bana_old_df.apply(lambda row: min_distance(row["lat"], row["lng"], station), axis=1)
bana_old_df["dist_bus_stop"]   = bana_old_df.apply(lambda row: min_distance(row["lat"], row["lng"], bus_stop), axis=1)
bana_old_df["cnt_crosswalk"] = bana_old_df.apply(lambda row: count_within(row["lat"], row["lng"], crosswalk), axis=1)
bana_old_df["is_road"]     = bana_old_df.apply(lambda row: is_roadside(row["lat"], row["lng"], road), axis=1)
bana_old_df

,nm,type,apv_date,addr,floor,sitearea,lat,lng,flpop_type,trdar_cd,...,flpop_dinner,flpop_etc,cnt_academy,cnt_hospital,cnt_school,cnt_company,dist_station,dist_bus_stop,cnt_crosswalk,is_road
0,바나프레소 테헤란로점,커피숍,2019-05-23,서울 강남구 테헤란로 208,1.0,98.40,37.501130,127.039099,TR,3120197.0,...,882135.00,752222.8125,0,1,0,0,223.598018,24.766102,8,1
1,바나프레소 신논현역점,커피숍,2019-08-06,서울 서초구 사평대로 364,1.0,107.24,37.503733,127.023196,TR,3120187.0,...,788268.00,560948.1250,0,1,0,0,765.979395,57.031538,18,1
2,바나프레소 선릉공원점,커피숍,2021-07-23,서울 강남구 테헤란로63길 20,1.0,97.28,37.506522,127.050398,TR,3120210.0,...,983513.00,833761.1250,1,2,0,0,258.610257,139.653177,16,1
3,바나프레소 충무로점,커피숍,2022-09-19,서울 중구 필동로 15,1.0,148.43,37.560339,126.996257,TR,3120032.0,...,362848.50,287171.8750,0,0,0,0,209.265490,165.181903,21,1
4,바나프레소 홍대입구역사거리점,커피숍,2022-11-07,서울 마포구 양화로 129,1.0,33.00,37.555061,126.920694,TR,3120102.0,...,552486.25,389756.6250,0,1,0,0,332.299469,58.952811,36,1
5,바나프레소 양재이안점,커피숍,2023-01-31,서울 서초구 강남대로34길 7,1.0,48.33,37.483032,127.036465,TR,3120179.0,...,473092.50,400709.2500,0,1,0,0,196.929245,68.322979,12,1
6,바나프레소 여의도파크원점,커피숍,2021-03-18,서울 영등포구 여의대로 108,-1.0,59.16,37.525191,126.929113,TR,3120149.0,...,317197.25,246954.3125,0,0,0,0,392.144845,28.172926,27,1
7,바나프레소 양평역점,커피숍,2015-08-05,서울 영등포구 양산로 43,1.0,59.40,37.525761,126.887942,TR,3120135.0,...,68874.00,71096.8750,0,0,0,5,98.907836,50.168375,24,1
8,바나프레소 명동중앙우체국점,커피숍,2021-10-29,서울 중구 명동8나길 51,1.0,193.85,37.561080,126.982077,TR,3120028.0,...,410975.75,273562.8125,0,1,0,0,341.656695,57.127609,16,1
9,바나프레소 마포역점,커피숍,2015-11-17,서울 마포구 마포대로 34,1.0,33.00,37.539260,126.946152,TR,3120106.0,...,141110.00,142316.5000,0,1,0,0,41.330683,61.846039,31,1

# 4. 경쟁사 비교 점수 변수

In [56]:
cafe_nm = cafe['nm']
cafe_nm = cafe_nm.to_list()
cafe_nm

['베레베레',
 '덕수궁전통차전문',
 '엘빠소',
 '씨애틀즈베스트커피대사관점',
 '본솔카페',
 '링고요고',
 '토넷트커피숍',
 '썬휴게실',
 '네스카페',
 '루비콘플러스',
 '구스토',
 '아름다운고궁',
 '피카디리망고 일리',
 '소그노스에스프레소',
 '노모토커피',
 '주)키커피코리아',
 '강남커피숍',
 '캔모아',
 '북카페내서재',
 '플로리안',
 'BABIANA(바비아나)',
 '숭실대생협 아름다운세상',
 '보보스',
 '에스프레소인뉴욕',
 '할리스커피(Hollys Coffee)',
 '제일상회',
 '국립고궁박물관 뮤지엄숍',
 '모드뜨레',
 '카페돌로미티',
 '카페하임',
 '미래월드',
 '커피501(coffee501)',
 '메리메이트(MerryMate)',
 '귀천',
 '탐앤탐스노원점',
 '커피투어(Coffee Tour)',
 '쿠벅양평점',
 '세리커피(Coffee)',
 '테라 스위트(Terra sweet)본점',
 '물커피(Mool Coffee)',
 '세븐일레븐(서울시립대점)',
 '#11(Sharp eleven)',
 '커피보노',
 'ATM(에이티엠)',
 '미르엠(MIRM)',
 '토프레소 태평로점',
 'POLE243',
 'Meister haus',
 '빈스빈스',
 '이디야커피',
 '소풍',
 '다동커피집',
 '파나마',
 '동네커피',
 '영화에 빠진 커피',
 '두루',
 '니들 북',
 '헤이리커피공장103이촌점',
 '퓨얼리데카던트',
 '이디야올림픽공원점',
 '카페베네 종로5가점',
 '이디야 서대문점',
 '남산커피집',
 '보티',
 '커피데이',
 '아산엠 매점',
 '까사안띠구아',
 '커피홀릭',
 '카페깔리아리',
 '파반커피',
 '카페나루',
 '카페라비',
 '투미',
 '호텔디아망',
 '빈스커피',
 '투썸플레이스',
 '야노아',
 'An.s coffee',
 '슐레스',
 '알엔비스커피(RNBS COFFEE)',
 '아임빈',
 '바오밥나무 여성미래센터점',
 '명동커피',
 '이디야커피명동중앙점',
 '지유명차 종로점',
 '엔오투',
 '세븐일레븐 종로효제점',
 '카페 더 단골',
 '올댓커피(All That Coffee)',
 '코피루왁',
 '소호앤노호',
 '더디퍼커피(The dipper coffee)',
 '카페에츠(cafe ats)',
 'cafe ICAM',
 '이디야성수아카데미점',
 '북카페',
 '카페 빈',
 '이디야커피',
 '비전케어',
 '커피락',
 '요거프레소 을지로3가점',
 '밀라노',
 '카페(cafe)1895',
 '이디야 커피 노량진 CTS점',
 '커피지인',
 '오즈',
 '미니스톱 종로육의전점',
 '김종영미술관 카페',
 '커피스푼',
 '커피산책',
 '모모웨이',
 '커피마마',
 '엑스퍼트마트(expat mart)',
 '드립하우스',
 '어컵오브(a cup of)',
 '힐',
 '셰이드트리',
 '갓구운커피 7',
 'in the same place (인더세임플레이스)',
 '그라나다카페',
 '커피데이',
 '이디야 마포오벨리스크점',
 '오리엔탈하우스',
 '빈트리이백이십오',
 '디데이 라운지 (D.day 라운지)',
 '커피마리오',
 '카페도드리',
 '테라로사',
 '피터팬과돈키호테/JH산업개발',
 '실로암',
 '아자부(동부이촌점)',
 '파스쿠찌 신사역점',
 '웰런커피',
 '오후',
 '맘스키친(Mom.s kitchen)',
 '위지안',
 '카페라또',
 '구스토(GUSTO)',
 '재재 종로점',
 '리얼커피',
 '파스쿠찌 두타점',
 '카페구로',
 '리시오',
 '카페 라이네케',
 '카페네스카페신천TS점',
 '사포리토',
 '할리스커피(회기역점)',
 '커피하이',
 '엠 커피 카페',
 '컵앤컵',
 '히읗',
 '커피바이(coffeebuy)',
 '아트센터나비미술관(카페나비)',
 '커피가 있는풍경',
 '카페드람브르',
 '커피야 구의점',
 '커피아마토르',
 'Berry.s Cookie(베리스쿠키)',
 '모나코',
 '14번지(14St.)',
 '블레스(Bless)',
 '야고비네',
 '57번가 카페',
 '성북동350',
 '와플베르비에',
 '토프레소',
 '이디야(회현SK리더스점)',
 '153 cafe',
 '하늘공원 사주카페',
 '커피나누기',
 '꿈을볶는커피하우스',
 '커피브론즈(COFFEE BRONZE)',
 '더힐커피',
 '뷰티플건강&coffee',
 '케냐키암부',
 '카페카페(cafe & cafe)',
 '카페도쎄(Cafe Doce)',
 '티나모우',
 '지에스(gs)25 화곡영광점내',
 '더빈스11(The Beans11)',
 '커피집(Coffee Zip)',
 '커피좀비',
 '하이디하우스',
 '챔프',
 '카페라네',
 '올 소울스',
 '로티보이 구로점',
 '더커피샵(The coffee #)',
 '호밀밭의 호두꾼',
 '이디야대림역점',
 '써니빈커피',
 '신스커피(Shin.s Coffee)',
 '아리스타커피(ARISTA COFFEE)',
 '코피 발리',
 '134-2',
 '라루',
 '보야',
 '카페베네 청량리1호점',
 '카페블라썸',
 '몽애',
 '미스터빈(Mr.Bean)',
 '스치브카페',
 '해피커피',
 '이디야커피',
 '레뚜라(Letter to Latte)',
 '김.Coffee',
 '2카페(2Cafe)',
 '얼음나무',
 '커피스탠드',
 'Cafe 곰퀼트',
 '보아스',
 '이름없는가게',
 '동네목수의 작은카페',
 '카페1온스',
 '옥정',
 '가비1896',
 '토마토',
 '스튜디오27',
 '카페두드림',
 '154 SooDa(수다)',
 '이디야 커피',
 '놀이터',
 '두란노서원',
 '숲',
 '아프리카눈',
 'suga(수가)',
 '플라워카페 에일린',
 '소월길커피',
 '씨유 종로신영점',
 '가배두림',
 '토프레소',
 '행복카페',
 '버즈커피',
 '아라누리',
 '커피베이 용두점',
 'CAFE NO 37(37번지 카페)',
 '델트렌 미아삼거리역지점',
 '커피베이(신당점)',
 'Blessing House(블레싱 하우스)',
 '아르디카페영등포점',
 '이디야(사가정점)',
 '파구스카페중계점',
 '마니커피숍',
 '카페감(gam)',
 '(주)케이씨 코퍼레이션 잠실지점',
 '로리엔',
 'Jazzda카페',
 '메종르베이지',
 '빈스브라운',
 '올리볼렌',
 '카페디어빈',
 '까페플러스',
 '카페 달콤한 오늘',
 '첼리나',
 '토프레소 고척점',
 '빅스트로우',
 '정인카페로뎀',
 '빈스토리',
 '미스터부커피',
 '르쇼아(LECHOIX)',
 '라리마(Larimar)',
 '착한유기농까페다정다감',
 '카페오',
 '카페 인(Cafe in)',
 '계화커피숍',
 '녹색푸드',
 '이디야',
 '카페말로여의3호점',
 '더카페',
 '크리미티',
 '스위트번스',
 '랠리까페',
 '커피 소사이어티(coffee society)',
 'SOO(수)',
 '머미',
 '밀알카페',
 '코너샵카페',
 '디어무이',
 '커피메이킹',
 '더퍼즐',
 'ABOUT 책과 머피',
 '카페 고릴라',
 '이디야커피 보라매공원점',
 'coffee song(커피송)',
 '바오밥나무',
 '커피 가지고',
 '길모퉁이 까페 다락',
 '공작',
 'M플레이카페 구의점',
 '카페 디아떼',
 '토프레소 상계3동점',
 '카페홍',
 '성북동 콩집',
 '큐비드',
 '더 메디 라운지',
 '커피알(coffee R)',
 '힐링스커피',
 '카페라또',
 '심플커피',
 '카페인(Cafe in)',
 '미스터 브리즈커피',
 '시즌아이',
 '원추(ONE CHU)',
 '이디야커피',
 '커피스튜디오',
 '(주)에이치제이텔레컴',
 '(주)인벤토커피',
 '스위티푸드',
 '공차 공평점',
 '애니하우스',
 '커피베이 종묘위너스점',
 '꽃이 바람이',
 '히든 스페이스',
 '베네치아',
 '디자이너스 카페인',
 '카페에일린',
 '반지만들기 대학로본점',
 '카페하우스',
 '까페 더 트리(cafe THE TREE)',
 'Salon de tearoom 미스홍자',
 '위드모리With morrie',
 '토프레소 낙성대역점',
 '카페 헤쎄드',
 '벨라지오',
 '사과나무',
 '이즈빈',
 '카페디트레블(CAFE DI TRAVEL)',
 '공차(GONG CHA-貢茶)교대점',
 '딱지야',
 '이층까페',
 '커피베이',
 '네츄럴웨이브카페',
 '에이플러스마트',
 '카페블루오',
 '카페바운스',
 '써니사이드카페',
 '소소와흐뭇',
 '이지웨이 두산타워점',
 '상가(Sangha)',
 '월드베스트커피',
 '원 빈(one bean)',
 '이디야 신림미성점',
 '빈스 스퀘어',
 '까페베네(충무로역점)',
 '카페 드롭탑',
 '달콤한 커피 방앗간',
 '어카페',
 '소풍',
 '더카페 가산2호(우림)',
 '공차',
 '주빈커피마에스더',
 '달달한카페',
 '진서의 정원',
 '카페 주네',
 'Cafe Namu 영우 성균관대',
 '공차대림점',
 '지니스카페',
 '라루라루',
 'Frank(프랭크)',
 '나인커피로스터스',
 '사단법인 사랑플러스',
 '카페리시오(cafe risio)',
 '디자이너주',
 '파스쿠찌 뱅뱅사거리점',
 '진솔커피숍',
 '000간',
 '(주)케이씨코퍼레이션 낙성대지점',
 '레벤스가든',
 '카플러스',
 '(주)디자인 포비 지브릭커피',
 '커피마마',
 '가회 한경헌',
 '북카페산책3호 산학협력센터점',
 '카페리치',
 '커피랩세아점',
 '카페린다린다린다',
 '아스트로노머스커피',
 '카페 휴',
 '카페7그램',
 'cafe-in 세종',
 '커피바이커피',
 '카페 머물다',
 '미스터브리즈커피',
 '통인 길 커피점',
 '허슬블렌딩',
 '첫만남',
 '플러스 커피앤코',
 '한나식빵',
 '작은카페',
 '이광수별장 춘원헌',
 '챔프 커피',
 '에이그레이트 도심공항터미널점',
 '이디야커피 신도림테크노마트점',
 '커피소리',
 '엘가(Lga)',
 '띠아모강변점',
 '커피한잔',
 '카페다 커피(독립문점)',
 '커반',
 '시드누아 가든파이브점',
 '로렌스테이블',
 '디바인그라인드',
 '타이거에스프레소',
 '선길',
 '키다리아저씨',
 '미노스(MINOS)',
 '더힐스낵',
 '카페플레이버',
 '502커피',
 '의료법인 청구성심병원점',
 '공차 구로디지털 2호점',
 '둘레길 쉼터 카페',
 '이디야커피',
 '북촌협동조합',
 '에스프레소버킷',
 '더카페엔여의도백화점점',
 '반지만들기 카페',
 '모노레일에스프레소 잠실삼성생명점',
 '모노레일커피여의도한화증권점',
 '카페오리(cafe ORI)',
 '광림교회 사회봉사관',
 '커피 맬러드',
 '스위트번스',
 '(주)프랜즈디자인',
 '블루 케틀',
 '웰어스',
 '이디야커피중계롯데우성점',
 '다락방(DALAGBANG)',
 '카페모찌',
 '인터밸리 커피',
 '루돌프의 레시피',
 '자연물들이기(전통농촌문화연구소  영농조합법인)',
 '세븐몽키스커피',
 '오메가라이더카페',
 '할리스 도심공항점2',
 '세라띠에커피공방',
 '미스터브리즈커피대림점',
 '커피노트',
 '인더랩(In The Lab)',
 '와플반트 제일병원 2호점',
 '커피그리고',
 '노란코끼리 수유점',
 '올리브 스콘',
 '스테이블 커피 로스터스',
 'ESPERE COFFEE(에스페레 커피)',
 '카페 얍',
 '그린',
 '카페프로방스',
 '미스터브리즈(Mr.Breeze)',
 '커피트리',
 '카페블라썸',
 '아마스빈여의도2호점',
 '퀸시바',
 '사이버존',
 '커피팡',
 '산울FNC',
 '와하하커피',
 '커피허니',
 '빠니니에꽁빠니(Panini et compagnie)',
 '커피향기',
 '요거프래소화곡푸르지오',
 '비안빈',
 '커피이레',
 '달수다',
 '엔제리너스 광장점',
 '그레이스(Grace)',
 '낙랑파라',
 '네스카페(남산점)',
 '카페마루',
 '투썸플레이스 강남자곡점',
 '이디야커피',
 '닥터스커피(강남)',
 '브릴리언트 커피로스터즈',
 '언덕위에',
 'SERENDIPITY(세렌디피티)',
 '블랑드블랑',
 '선유도커피집 은마',
 '스탄자',
 '커피농장의하루',
 '민트레빗',
 '카페하루',
 '카미노커피로스터스',
 '앵글러 빈',
 '세븐몽키스중곡점',
 '더치즈케이크',
 '샘',
 '민스 빈',
 '코코버블티 신논현점',
 '이디야커피목동신목점',
 '설화(sulhwa)',
 '이디야커피 해군회관점',
 '라붐(LaBoum)',
 '빈스밀',
 '도깨비커피집',
 '에세이(S.A)',
 '가온길',
 '더 채임버 52',
 '공차현대아울렛 가산점',
 '더나우커피',
 '더레드(THE RED)',
 '스튜디오 잇(Studio EAT)',
 '설빙',
 '아마스빈코리아 목동파리공원점',
 '더 한옥',
 '커피업(Coffee Up)',
 '카페(cafe)711',
 '카페 아이리스 (cafe IRIS)',
 '일 나뚜랄레',
 '카페 리브레',
 '또또(TonTon)',
 '코이노니아(Koinonia)카페',
 '카페 애프터유(cafe AfterU)',
 '요거프레소 화곡점',
 '금보성 아트센터',
 '더카페엔여의도백화점점',
 '이디야커피 한국은행점',
 '이디야커피합정LIG점',
 '남산카페',
 '아이스빌리지',
 '퓨엘앳센티넬IFC(Fuel at sentinel IFC)',
 '산과산사이커피로드',
 '리브스 커피(Leaves Coffee)',
 '미라보',
 '더 체어',
 '카페슈몽',
 '드플로허',
 '카페띠아모',
 '디자인포디움',
 '(유)엠에프리테일 노원점',
 '카페 쉐어링 동양생명점',
 '커피라움',
 '와플반트',
 '토이셔',
 '삼바존코리아',
 '아메리카노',
 '델트렌 충무로역지점',
 '(주)비바브라질',
 '탐앤탐스 일원점',
 '앤티앤스 프레즐',
 '설나루',
 '씨즈캔디',
 '퀴즈노스 역삼점',
 '유니유니베이비카페',
 'S카페',
 '카페아임',
 '토리베이커리 카페',
 '투달러스커피(TWO DOLLARS COFFEE) 1호점',
 '(주)아셈플라워랜드',
 '커피 휴',
 'TEA M(티 엠)',
 '까페 봉주르마담(CAFE BONJOUR MADAME)',
 '고와카페',
 '카페하이',
 '커피베이 월곡역점',
 '드립앤더치명동중앙점',
 '다인스카페 연지점',
 '엠모터스',
 '바로커피',
 '미스터투고 커피 앤 디저트',
 '프렌즈카페',
 '드링크박스(Drink Box)',
 '커피앤버블(Coffee&Bubble)',
 '셀렉토커피 동묘역점',
 '카페 이브닝',
 '석관동떡볶이 대학로점',
 '라떼앤퐁당',
 '본정초코릿',
 '(주)닥터케이포뮬러',
 '호텔데님카페',
 '커피투고',
 '요거프레소',
 '모 네',
 '씨유편의점',
 '카페 21g',
 '피자스쿨상왕십리역점',
 '카페오아시아',
 '까페 뷰',
 '배스킨라빈스 서울대입구역점',
 'Cafe Stay(카페 스테이)',
 '씨앗플러스',
 '유오디아(Euodia)',
 '커피베이 온수힐스테이트점',
 'BANJO(반조)',
 '감나무아래',
 '더컬러',
 '핸드드립드로우(HAND Drip Draw) 커피콩',
 '엔젤디오커피',
 '커피올렌스',
 '커피N빙수',
 '까로치아용산점',
 '카페보니또영등포1호점',
 '이디야커피',
 '리얼크레마',
 '이디야커피동서울터미널점',
 '립스티',
 '망개떡 성순자 아시아점',
 '더치 앤 빈',
 '레몬트리',
 '로뎀나무카페',
 '반지대학명동캠퍼스',
 '얼티밋쿠반(ultimate cuban)',
 '햅시바',
 'the cafe 36.5(더 카페 36.5)',
 '카페바움',
 '커피블루그린(Coffee Blue Green)',
 '카페더메드',
 '오가다용산아이파크몰점',
 '미스 쇼콜라',
 '크라프트카페',
 '메홀라카페',
 '꿈꾸는 고래',
 '갤러리 비즈엔아트카페',
 '아로이 커피(연신내점)',
 '가비 커피로스터스',
 '보드스쿨',
 '카페본',
 '요거프레소 노원문화점',
 '카와블러썸',
 '미스터브리즈커피',
 '카페 모아',
 '하일라 카페',
 '스피키지 인 모네(Speakeasy in Monet)',
 '카페레아(CAFE RHEA)',
 '커피 스테이션 (COFFee station)',
 '수 커피볶는집',
 '커피나무',
 '요거프레소장안점',
 'Coffee with',
 'OMG도넛앤커피',
 '이츠이매지컬',
 '투썸플레이스 까치산역점',
 '육미분식',
 '스마일콩(Smile Kong)',
 '요벨',
 '카페 에쏘미오(ESPRESSO MIO)',
 '청소년휴카페꽃다방',
 '키노빈스',
 '빽다방 반포고투몰점',
 '커피밀',
 '오크라',
 'now&here(나우&히얼)',
 '카페도도',
 '쿰파(KUMFA)공익카페파구스케이비(KB)엔젤맘',
 '(주) 리투스코리아',
 '민트프랜트',
 '이상',
 '테일러커피',
 '큐카페',
 '투썸플레이스서울대역중앙점',
 '지오북카페',
 '미스터로티',
 '커피마마',
 '홈스테이',
 '새들깃든겨자나무',
 '공차 보라매점',
 'ANOPLA(아노플라)',
 '미남커피',
 '츄로101홍대본점',
 '투엑스라지커피',
 'cafe heaven(카페 헤븐)',
 '엘스',
 '명동반지카페 설레임',
 '카카오 PC방',
 '쪼마카페강남점',
 '커피정',
 '최가커피',
 '도담카페',
 '자작나무',
 '구스띠모',
 '젬스커피',
 '통인사랑',
 'Art of coffee',
 '가락시장역점 빽다방',
 '커피스토어 네모(COFFEE STORE NEMO)',
 '할리스커피 코엑스점',
 '생두',
 '요거프레소 서울교대점',
 '커피829',
 '죠아찌쥬스',
 '아리스타공덕점',
 '가베5225',
 '크레이저커피 잠원점',
 '씨유목동파리공원점',
 '보성 전통찻집',
 '에이그레이트카페용산아스테리움점',
 '피피커피',
 'D샵(디샵)',
 '이디야망원중앙점',
 '에이(A)카페',
 '요거프레소',
 '커피집',
 '호텔볼(VOLL) 커피숍',
 '골목카페',
 '투오버',
 '세븐일레븐 태능입구역점',
 '카페비',
 '원남가베',
 'Di Di(디 디)',
 '커피트리',
 '월촌',
 '차중의차(Tea of teas)',
 '더까페',
 'TAKEAWAY',
 '아이엔유카페사랑신촌점',
 '유로스타커피 양재점',
 '바르다김선생당산역점',
 'GMCC(지엠씨씨)',
 '클렌치커피',
 '커피방앗간',
 '셀렉토커피방학역점',
 '빽다방(노원역우리은행점)',
 '설빙 사당역점',
 '.bout coffee(바웃 커피)',
 '공감',
 '카페 301',
 '빽다방 잠실역지하도점',
 '자모크',
 '이디야커피(하월곡동점)',
 '망고랑',
 '랑상텐',
 '카페디오',
 '올떡(GFAC점)',
 'tarte maman',
 '마루티샵',
 'CONA CAFE (코나카페)',
 '커피나무',
 '카페97 (CAFE97)',
 '핸즈온캠퍼스',
 '라부에노',
 '휘드카페 중계점',
 '빽다방 반포고투몰2호점',
 '언노운커피(Unknown coffee)',
 '벨포트',
 '커피친구',
 '슈어-슈어리 커피(Sure-Surely Coffee)',
 '더랩 서울대사범대점',
 '카페밀콩',
 '페어칠이오',
 '빽다방 우장산역점',
 '베리굿타임',
 'Fruit to go(푸룻투고)',
 '보니떼',
 '더느림 까페',
 '빽다방',
 '커피스테이션(coffee station)',
 '집',
 '(주)씨앤지풀서비스 흥국제선점',
 '밀리타전시장',
 '빽다방 강동역 헤르셔점',
 '플로릭카페',
 '피에로 커피',
 '고마워케이크',
 'The order(디오더)',
 '다올 커피',
 '카페 투 샷(cafe two shot)',
 '카페글로리',
 '크레마 181(Crema 181)',
 '해리스(카페더테이블)',
 '달달보드레',
 '카페수다(cafe suda)',
 '위트러스트커피(WE TRUST COFFEE)',
 'D&C(디앤씨)',
 '재미로 테이크아웃',
 '밀랑스',
 '투썸플레이스 양재역점',
 '로스팅카페(Roasting Cafe)',
 '510파인애비뉴',
 '이디야 가재울 중앙점',
 '오파인 앤 라운지 카페',
 '이디야커피 신길역점',
 '더쎄컨',
 '조각커피',
 '커피베이 내방역점',
 '빽다방 송파 방이점',
 '포트오브모카 문정점',
 '데니스커피 남강점',
 '백운전통찻집',
 '카페마레',
 '카페다담',
 '헬라스커피',
 '토크빈',
 '스케네',
 '플러스91',
 '카페 쉼터',
 'Pit a Pat (피터패트)',
 '명동커피숍',
 '테라하우스',
 '옐로우문',
 '떡 앤 도너츠',
 '호두왕찹쌀떡',
 '커피볶는중 카페김쌤',
 '카페플라워',
 '에스프레소웍스(더스콘)',
 '더카페엔숙대정문점',
 '컴플리트(COMPLETE) 6.8',
 '베이글카페(마포서교점)',
 '봉화산커피',
 '크레센도',
 '카페 몽타주',
 '훈고링고브레드',
 '빽다방 중랑역 동부시장점',
 '카페 잉거(cafe inger)독산점',
 '카페엔젤',
 '포스트카페',
 'P2 Coffee',
 '쑤앤쑤',
 '파파샌드',
 '카페91플러스(CAFE91+)',
 '드리퍼',
 '이디야 커피점',
 '쥬씨휘경점',
 'Coffee3Times(커피3타임즈)',
 '메리하하(Merry Haha)',
 '브레드 빈',
 '주스탐 압구정점',
 '(주)영우 명지전문대 커피점',
 '카페 디오이오',
 '빌리지 온',
 '후아나',
 '대루커피',
 '홍반장커피 구로점',
 '러브컵(LOVECUP)',
 '카페 수',
 '파오파오차(paopao cha)',
 '데코덴카페내맘케(decoden cafe 내맘케)',
 '젤라리소(Gelariso)여의도수정점',
 '레가타커피',
 '빽다방 남대문시장점',
 '착한커피',
 '이디야 가산리더스타워점',
 '이디야 남부터미널점',
 '카페 소금다방',
 '이디야',
 '아모르(Amor)',
 'Caffe Attico(카페아티코)',
 '쥬씨(압구정2호점)',
 '아로하 커피',
 '다오라커피',
 '엘리스 1871',
 '카페 트리니티블랙',
 'J.antique(장티크)',
 '센트코리아띠아모 한양대 HK점',
 'Saint Paul(쌩폴)',
 '카페트렌홍대점',
 '카페 숲',
 '하니앤손스',
 '까페부오노',
 '거리에서',
 '도노커피(국회의사당점)',
 '커피식스쥬스식스건대역점',
 '커피니 종로숭인점',
 '투썸 플레이스(신설IBC호텔점)',
 '셀렉토커피',
 '갤러리카페(Gallery cafe) NY',
 '이디야커피(혜화동로터리)',
 '노리(NORI)',
 '빙달회기점',
 '테이크온미커피',
 '명지대 빽다방',
 '휘카페',
 '엔제리너스커피롯데영등포역사점',
 '보일스커피',
 '만랩커피',
 '커피수기',
 '이디야(신정네거리역점)',
 '배재란의 커피클래스(이촌점)',
 '김종욱커피',
 '이디야커피',
 '어린이박물관카페도담도담',
 '카페마운틴',
 '초코츄츄',
 '(주)호텔리안',
 '미라클1 카페',
 '콘스탄스',
 '스윗레시피',
 '카페보다',
 '벨로마노한남점',
 '죠스테이블',
 '고다방 대치점',
 '올어바웃미',
 '미님',
 '베어(bear)',
 '이디야커피랩',
 '곰탱이커피',
 '갸또마마',
 '빨간모자웨딩카페',
 'GS25창동센터점',
 '아이파크문화센터',
 '쥬스나무',
 '테이크아웃',
 '배우;다',
 '르보(lebo)',
 '카페G',
 '크레노(몬스터리빙)',
 '강남 스테이(GANGNAM STAY)',
 'CODE101',
 '세븐일레븐',
 '이디야 화곡로점',
 '이디야 상봉중앙점',
 '에이미스커피',
 '요거프레소',
 '에듀테인먼트놀',
 '투고샐러드',
 '쥬스박스',
 '이디야',
 '네추럴카페 진락',
 '카페 수에르떼(Cafe Suerte)',
 '지간테커피 삼청동점',
 '김.멘',
 '커피 팟',
 '스탠스커피(STANCE COFFEE)',
 '쥬씨 난곡점',
 '놀숲 대학로점',
 '카페8(Cafe 8)',
 '쥬시 서일대점',
 '북촌이야기',
 '태양커피',
 '밀크커피',
 '헤르츠 인타임카페(Hz inTime Cafe)',
 '이디야커피(보라매역)',
 '퀼트 카페 인',
 '빽다방청량리역점',
 '에이미스 커피',
 '빽다방 신림역2호점',
 'cafe 라이스',
 '사이마켓',
 '학화호도과자',
 '커피브루(COFFEE BRU)',
 '인컴솔루션',
 'cafe in',
 '프렌치앤틱(French Antique)',
 '루나모디카',
 '드림스페이스(Dream Space)',
 '드림스페이스(Dream Space)',
 '에이미스커피 학동역점',
 '카페홀린',
 '코코부코 장충점',
 '포포PC방 중계역점',
 '세븐일레븐(마포성산본점)',
 '피에이씨그라운드(PAC GROUND)',
 '공방163',
 '하우스까페',
 '쓰리팝',
 '커피마리',
 '이디야당산중앙점',
 '코믹베어(Comic Bear)',
 '브라운팩토리',
 '하나커피',
 '79 THE LAB',
 '메르씨',
 '스타카토커피점',
 '미미당',
 '리틀랩 드링크 스탠다드',
 '카페토르토니',
 '지바트 은평점',
 '비공이',
 '그라운드 오리진',
 '제너럴포스트오피스',
 '세라그림(슬로비 씨투)',
 '별빛',
 '카카오다다',
 '셀렉토커피 논현점',
 '(주)펜카페코리아',
 '에스프레소카페티',
 '이디야커피',
 '3 HUNDRED COFFEE',
 '샤론꽃방',
 '티스퀘어',
 '커피폴리',
 '카페루(CAFE-루)',
 '소마 (SOMA)',
 '프라임인 서울호텔',
 '카페 엘림',
 '커피부스(coffee booth)',
 '아재의 취미',
 '헤일리스카페',
 'THE CAFFE(더 카페) 교대역점',
 '메가커피 신도림역점',
 '커피마마',
 '에스시티 스터디카페 협동조합',
 '카페차오',
 '꿈터로뎀카페',
 '데코아발림',
 '솜씨와 情떡',
 '코이카페(현대백화점 압구정점)',
 '이디야여의나루역점',
 'ㅋ오엔지(ONG)',
 '퓨로주스',
 '믹스(MIX)',
 '카페 아지트',
 '꾸미네 주전부리',
 '커피볶는 남자',
 '애플블러썸여의도2호점',
 '죽앤카페',
 '정아네',
 '빙달',
 '커피에이엠',
 '달커피',
 '다빈커피',
 '커피킹',
 ...]

In [85]:
# 1) 이름 정규화 함수
def norm(s):
    if pd.isna(s):
        return ""
    s = str(s).lower()
    s = re.sub(r"[\s\.\,\-\(\)\[\]\/_]", "", s)  # 공백/기호 제거
    return s

# 2) 브랜드 키워드(필요시 추가/수정)
LOW_PATTERNS = [
    "메가엠지씨", "메가mgc", "메가커피",
    "빽다방",
    "컴포즈", "compose",
    "더벤티", "theventi",
    "매머드", "mammoth",
    "텐퍼센트", "tenpercent",
    "커피베이",
    "우지커피", "oozy",
    "백억커피",
    "벤티프레소", "ventipresso",
]

HIGH_PATTERNS = [
    "스타벅스", "starbucks",
    "투썸", "twosome",
    "폴바셋", "paulbassett",
    "커피빈", "coffeebean",
    "할리스", "hollys",
    "아티제", "artisee",
    "테라로사", "terarosa",
    "오설록", "osulloc",
]

BANA_PATTERNS = ["바나프레소", "banapresso"]

def contains_any(text, patterns):
    return any(p in text for p in patterns)

# 3) 분류 함수
def cafe_tier(name):
    x = norm(name)
    if contains_any(x, BANA_PATTERNS):
        return "banapresso"
    if contains_any(x, HIGH_PATTERNS):
        return "high"
    if contains_any(x, LOW_PATTERNS):
        return "low"
    return "etc"

# 4) 적용
cafe["detail"] = cafe["nm"].apply(cafe_tier)

# 확인
print(cafe["detail"].value_counts())
cafe.head()

detail
etc           11197
low            2209
high           1071
banapresso       59
Name: count, dtype: int64

,nm,type,apv_date,addr,floor,sitearea,lat,lng,flpop_type,trdar_cd,adstrd_cd,detail
0,베레베레,커피숍,2002-09-19,서울 광진구 능동로13길 19,NaN,NaN,37.542885,127.070832,TR,3120053.0,11215710,etc
1,덕수궁전통차전문,커피숍,2003-01-16,서울 중구 서소문로 109,2.0,46.28,37.563062,126.973280,TR,3120020.0,11140520,etc
2,엘빠소,커피숍,2003-05-31,서울 종로구 성균관로 18,NaN,NaN,37.584406,126.997641,TR,3110021.0,11110650,etc
3,씨애틀즈베스트커피대사관점,커피숍,2003-10-31,서울 종로구 세종대로 188,1.0,NaN,37.573190,126.977831,AD,NaN,11110615,etc
4,본솔카페,커피숍,2004-01-17,서울 용산구 청파로47길 71,1.0,13.80,37.544840,126.966455,TR,3110069.0,11170555,etc

In [93]:
# 0) detail 매핑
detail_map = {
    "banapresso": "cnt_banapresso",
    "high": "cnt_high_cafe",
    "low": "cnt_low_cafe",
    "etc": "cnt_etc_cafe"
}

# 1) 함수 정의
def count_cafes_nearby(cafe_lat, cafe_lon, cafe_idx, cafes_df, radius=300):
    # 자기 자신 제외
    other_cafes = cafes_df.drop(index=cafe_idx)
    
    mask = other_cafes.apply(
        lambda row: haversine(
            (cafe_lat, cafe_lon), (row["lat"], row["lng"]), unit=Unit.METERS
        ) <= radius, axis=1
    )
    nearby = other_cafes[mask]
    counts = nearby.groupby("detail").size()
    
    # 없는 type도 0으로 채우기
    counts = counts.reindex(detail_map.keys(), fill_value=0)
    counts.index = [detail_map[d] for d in counts.index]
    return counts

# 2) 적용
result = bana_old_df.apply(
    lambda row: count_cafes_nearby(row["lat"], row["lng"], row.name, cafe),
    axis=1
).fillna(0).astype(int)

bana_old_df = pd.concat([bana_old_df, result], axis=1)
bana_old_df

,nm,type,apv_date,addr,floor,sitearea,lat,lng,flpop_type,trdar_cd,...,cnt_school,cnt_company,dist_station,dist_bus_stop,cnt_crosswalk,is_road,cnt_banapresso,cnt_high_cafe,cnt_low_cafe,cnt_etc_cafe
0,바나프레소 테헤란로점,커피숍,2019-05-23,서울 강남구 테헤란로 208,1.0,98.40,37.501130,127.039099,TR,3120197.0,...,0,0,223.598018,24.766102,8,1,1,6,6,27
1,바나프레소 신논현역점,커피숍,2019-08-06,서울 서초구 사평대로 364,1.0,107.24,37.503733,127.023196,TR,3120187.0,...,0,0,765.979395,57.031538,18,1,1,6,8,36
2,바나프레소 선릉공원점,커피숍,2021-07-23,서울 강남구 테헤란로63길 20,1.0,97.28,37.506522,127.050398,TR,3120210.0,...,0,0,258.610257,139.653177,16,1,1,1,10,25
3,바나프레소 충무로점,커피숍,2022-09-19,서울 중구 필동로 15,1.0,148.43,37.560339,126.996257,TR,3120032.0,...,0,0,209.265490,165.181903,21,1,1,4,5,31
4,바나프레소 홍대입구역사거리점,커피숍,2022-11-07,서울 마포구 양화로 129,1.0,33.00,37.555061,126.920694,TR,3120102.0,...,0,0,332.299469,58.952811,36,1,1,4,4,28
5,바나프레소 양재이안점,커피숍,2023-01-31,서울 서초구 강남대로34길 7,1.0,48.33,37.483032,127.036465,TR,3120179.0,...,0,0,196.929245,68.322979,12,1,1,6,5,20
6,바나프레소 여의도파크원점,커피숍,2021-03-18,서울 영등포구 여의대로 108,-1.0,59.16,37.525191,126.929113,TR,3120149.0,...,0,0,392.144845,28.172926,27,1,1,3,1,24
7,바나프레소 양평역점,커피숍,2015-08-05,서울 영등포구 양산로 43,1.0,59.40,37.525761,126.887942,TR,3120135.0,...,0,5,98.907836,50.168375,24,1,1,1,2,15
8,바나프레소 명동중앙우체국점,커피숍,2021-10-29,서울 중구 명동8나길 51,1.0,193.85,37.561080,126.982077,TR,3120028.0,...,0,0,341.656695,57.127609,16,1,1,5,4,62
9,바나프레소 마포역점,커피숍,2015-11-17,서울 마포구 마포대로 34,1.0,33.00,37.539260,126.946152,TR,3120106.0,...,0,0,41.330683,61.846039,31,1,1,2,4,14

# 중간 저장(csv로 내보내기)

In [94]:
bana_old_df.to_csv("bana_old.csv", index=False, encoding="utf-8-sig")

# 5. 수요 + 접근성 + 경쟁사 점수