In [29]:
import requests 
import os
from dotenv import load_dotenv
import pandas as pd

In [79]:
# env 파일 로드
load_dotenv()

True

# 지식산업센터

## 데이터 불러오기

In [27]:
apikey  = os.getenv("MJ_APIKEY")     # 인증키
start_index = "1"    # 요청시작위치
end_index   = "300"  # 요청종료위치

url = f"http://openapi.seoul.go.kr:8088/{apikey}/json/InfoBizcenterApply/{start_index}/{end_index}/"

response = requests.get(url)
print(response.content.decode('utf-8'))

{"InfoBizcenterApply":{"list_total_count":213,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다"},"row":[{"IDX":208.0,"FAC_NM":"신내테크노타운","ADDRESS":"봉화산로 123(상봉동)","TELEPHONE":"02)3423-0057","APPROVAL_DATE":"96.5.28","COMPLE_DATE":"99.10.18"},{"IDX":136.0,"FAC_NM":"월곡동아파트형공장","ADDRESS":"하월곡동 96-113","TELEPHONE":"02-090-8083","APPROVAL_DATE":"33289","COMPLE_DATE":"1990.12.31"},{"IDX":135.0,"FAC_NM":"월곡동아파트형공장","ADDRESS":"하월곡동 96-113","TELEPHONE":"02-912-1034","APPROVAL_DATE":"33289","COMPLE_DATE":"1990.12.31"},{"IDX":140.0,"FAC_NM":"문정아르페온 1차 지식산업센터","ADDRESS":"서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)","TELEPHONE":"031-706-8577","APPROVAL_DATE":"2016.06.27","COMPLE_DATE":"2016.06.27"},{"IDX":139.0,"FAC_NM":"문정 대명벨리온","ADDRESS":"서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)","TELEPHONE":"02-2222-7357","APPROVAL_DATE":"2016.03.23","COMPLE_DATE":"2016.03.23"},{"IDX":141.0,"FAC_NM":"문정 현대지식산업센터Ｉ-1","ADDRESS":"서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)","TELEPHONE":"02-3451-0100","APPROVAL_DATE":"2016.02.29","COMPLE_DATE":"2016.02.29"},{"IDX":138.0,"FAC_NM":"송파유탑테크밸리","ADDRESS":"서울특별시 송파구 문정동 651-14 (문정도시개발구역 3-12BL)","TELEPHONE":"062-526-8383","APPROVAL_DATE":"2015.12.18","COMPLE_DATE":"2015.12.18"},{"IDX":207.0,"FAC_NM":"포휴","ADDRESS":"성수동1가 656-3","TELEPHONE":"3416-1500","APPROVAL_DATE":"2013.08.30","COMPLE_DATE":"2016.5.3"},{"IDX":117.0,"FAC_NM":"에이스하이엔드타워 10차","ADDRESS":"가산동 660","TELEPHONE":"6309-6045","APPROVAL_DATE":"2013.08.29","COMPLE_DATE":"2015.10.28"},{"IDX":206.0,"FAC_NM":"BY센터","ADDRESS":"성수동2가 301-51,301-38","TELEPHONE":"(02) 467-2247","APPROVAL_DATE":"2013.08.12","COMPLE_DATE":"2015.12.04"},{"IDX":205.0,"FAC_NM":"신한IT타워","ADDRESS":"성수동1가 656-603","TELEPHONE":"","APPROVAL_DATE":"2013.07.02","COMPLE_DATE":"2015.06.04"},{"IDX":116.0,"FAC_NM":"에스비즈니스센터","ADDRESS":"가산동 343-8","TELEPHONE":"2163-6749","APPROVAL_DATE":"2013.03.26","COMPLE_DATE":"2015.06.01"},{"IDX":165.0,"FAC_NM":"선유도역2차 아이에스비즈타워","ADDRESS":"선유로49길 23(양평동4가)","TELEPHONE":"6123-4100","APPROVAL_DATE":"2012.12.18","COMPLE_DATE":"2014.11.19"},{"IDX":115.0,"FAC_NM":"대륭테크노타운17차","ADDRESS":"가산동 670","TELEPHONE":"3466-0051","APPROVAL_DATE":"2012.12.10","COMPLE_DATE":"2015.05.15"},{"IDX":204.0,"FAC_NM":"서울숲\n드림타워(삼공)","ADDRESS":"성수동2가 323, 309-51","TELEPHONE":"(02)6222-8114","APPROVAL_DATE":"2012.10.31","COMPLE_DATE":"2015.03.23"},{"IDX":164.0,"FAC_NM":"에이스하이테크시티 2","ADDRESS":"선유로13길 25(문래동6가)","TELEPHONE":"2257-8114","APPROVAL_DATE":"2012.08.27","COMPLE_DATE":"2014.10.24"},{"IDX":2.0,"FAC_NM":"NICE그룹 지식산업센터","ADDRESS":"상일로6길 55 (상일동)","TELEPHONE":"2122-4415","APPROVAL_DATE":"2012.06.29","COMPLE_DATE":"2014.02.28"},{"IDX":166.0,"FAC_NM":"SK V1 center","ADDRESS":"당산로41길 11(당산동4가)","TELEPHONE":"6121-8100","APPROVAL_DATE":"2012.06.19","COMPLE_DATE":"2015.02.17"},{"IDX":203.0,"FAC_NM":"서울숲IT캐슬","ADDRESS":"성수동1가 671-6, -41 외 4필지","TELEPHONE":"(02) 2086-3346","APPROVAL_DATE":"2012.05.10","COMPLE_DATE":"2014.06.17"},{"IDX":1.0,"FAC_NM":"세종투자㈜","ADDRESS":"강동구 상일로10길 36 (상일동)","TELEPHONE":"3415-4971","APPROVAL_DATE":"2011.11.30","COMPLE_DATE":"2013.09.13"},{"IDX":202.0,"FAC_NM":"에이스하이앤드\n 성수타워","ADDRESS":"성수동2가 269-25,269-51,\n269-115,328-5","TELEPHONE":"(02) 2112-6491","APPROVAL_DATE":"2011.11.15","COMPLE_DATE":"2015.06.19"},{"IDX":201.0,"FAC_NM":"에이스성수타워1차","ADDRESS":"성수2가 280-15,19","TELEPHONE":"(02) 591-0607","APPROVAL_DATE":"2011.10.20","COMPLE_DATE":"2014.03.11"},{"IDX":52.0,"FAC_NM":"G플러스 코오롱 디지털타워","ADDRESS":"구로동 222-31","TELEPHONE":"858-3650","APPROVAL_DATE":"2011.06.09","COMPLE_DATE":"2013.7.24"},{"IDX":163.0,"FAC_NM":"선유도역1차 아이에스비즈타워","ADDRESS":"양평로21길 26(양평동5가)","TELEPHONE":"6968-1004","APPROVAL_DATE":"2011.04.21","COMPLE_DATE":"2013.5.27"},{"IDX":200.0,"FAC_NM":"서울숲\n한라시그마밸리II","ADDRESS":"성수동2가 333-15","TELEPHONE":"(02) 4199-5621","APPROVAL_DATE":"2011.02.25","COMPLE_DATE":"2013.03.28"},{"IDX":51.0,"FAC_NM":"대륭포스트타워7차","ADDRESS":"구로동 170-10 외 2필지","TELEPHONE":"6942-9500","APPROVAL_DATE":"2011.02.21","COMPLE_DATE":"2012.12.11"},{"IDX":10.0,"FAC_NM":"강서IT밸리","ADDRESS":"화곡로68길 82","TELEPHONE":"6961-5111","APPROVAL_DATE":"2010.3.9","COMPLE_DATE":"2012.2.6"},{"IDX":11.0,"FAC_NM":"강서한강자이","ADDRESS":"양천로 401","TELEPHONE":"6968-5801~2","APPROVAL_DATE":"2010.10.15","COMPLE_DATE":"2013.6.7"},{"IDX":199.0,"FAC_NM":"서울숲 \n한라에코벨리","ADDRESS":"성수동1가 656-36\n656-1222","TELEPHONE":"(02) 549-6693","APPROVAL_DATE":"2010.09.09","COMPLE_DATE":"2012.09.06"},{"IDX":198.0,"FAC_NM":"성수동\n아이에스비즈타워","ADDRESS":"성수동2가289-319,327,328","TELEPHONE":"(02) 3218-6643","APPROVAL_DATE":"2010.08.28","COMPLE_DATE":"2012.07.23"},{"IDX":162.0,"FAC_NM":"KnK디지털타워","ADDRESS":"영신로 220(영등포동8가)","TELEPHONE":"2675-6060","APPROVAL_DATE":"2010.08.27","COMPLE_DATE":"2012.12.07"},{"IDX":167.0,"FAC_NM":"문래동 하우스디 비즈","ADDRESS":"선유로3길 10(문래동5가)","TELEPHONE":"2112-6339","APPROVAL_DATE":"2010.08.10","COMPLE_DATE":"2016.05.09"},{"IDX":160.0,"FAC_NM":"선유도코오롱디지털타워","ADDRESS":"양평로22길21(양평동5가)","TELEPHONE":"2062-5996","APPROVAL_DATE":"2010.07.13","COMPLE_DATE":"2012.03.23"},{"IDX":197.0,"FAC_NM":"성수에이팩센터","ADDRESS":"성수동2가 289-5\n289-334,289-335","TELEPHONE":"(02) 3416-1541","APPROVAL_DATE":"2010.06.24","COMPLE_DATE":"2012.08.24"},{"IDX":196.0,"FAC_NM":"아연디지털타워","ADDRESS":"성수동2가314-37","TELEPHONE":"(02) 499-2275","APPROVAL_DATE":"2010.06.01","COMPLE_DATE":"2012.08.31"},{"IDX":195.0,"FAC_NM":"서울숲 SK V1 타워","ADDRESS":"성수동2가284-55, 284-107","TELEPHONE":"(02) 6233-8000","APPROVAL_DATE":"2010.04.13","COMPLE_DATE":"2014.07.18"},{"IDX":114.0,"FAC_NM":"에이스하이엔드9차","ADDRESS":"가산동 481-2","TELEPHONE":"6309-6051","APPROVAL_DATE":"2010.04","COMPLE_DATE":"2012.07.20"},{"IDX":194.0,"FAC_NM":"서울숲\nIT 밸리","ADDRESS":"성수동1가 13-170\n외9필지(13-170,13-166,13-472,13-169,13-256,13-164,13-253,13-171,13-255,13-167)","TELEPHONE":"(02) 2090-8202","APPROVAL_DATE":"2010.03.24.","COMPLE_DATE":"2013.02.08"},{"IDX":50.0,"FAC_NM":"JnK 디지털타워","ADDRESS":"구로3동 222-3","TELEPHONE":"6124-6611","APPROVAL_DATE":"2010.01.20","COMPLE_DATE":"2012.2.15"},{"IDX":121.0,"FAC_NM":"대성D-POLIS","ADDRESS":"가산동 543-1","TELEPHONE":"861-9114","APPROVAL_DATE":"2009.12","COMPLE_DATE":"2012.09"},{"IDX":159.0,"FAC_NM":"동아프라임밸리","ADDRESS":"영등포로5길19(양평동2가)","TELEPHONE":"6210-7201","APPROVAL_DATE":"2009.10.21","COMPLE_DATE":"2011.11.25"},{"IDX":161.0,"FAC_NM":"솔버스 비즈타워","ADDRESS":"선유서로31길3(양평동3가)","TELEPHONE":"6963-8080","APPROVAL_DATE":"2009.10.19","COMPLE_DATE":"2012.09.05"},{"IDX":212.0,"FAC_NM":"동대문패션비즈센터 ","ADDRESS":"신당동 251-160","TELEPHONE":"070-8895-7347","APPROVAL_DATE":"2009.05.14","COMPLE_DATE":"2012.03.07"},{"IDX":129.0,"FAC_NM":"현대지식산업센터","ADDRESS":"독산동 291-1 ","TELEPHONE":"858-3080","APPROVAL_DATE":"2009.04","COMPLE_DATE":"2014.03.04"},{"IDX":193.0,"FAC_NM":"이레타워","ADDRESS":"성수동2가 277-175번지","TELEPHONE":"(02) 466-2663","APPROVAL_DATE":"2009.01.22","COMPLE_DATE":"2009.08.07"},{"IDX":9.0,"FAC_NM":"강서한화비즈메트로2차","ADDRESS":"양천로551-24","TELEPHONE":"6957-1990","APPROVAL_DATE":"2008.7.25","COMPLE_DATE":"2012.1.16"},{"IDX":8.0,"FAC_NM":"강서한화비즈메트로1차","ADDRESS":"양천로551-17","TELEPHONE":"6957-1990","APPROVAL_DATE":"2008.7.25","COMPLE_DATE":"2012.1.13"},{"IDX":113.0,"FAC_NM":"알에스엠타워","ADDRESS":"가산동 327-29","TELEPHONE":"2112-6300","APPROVAL_DATE":"2008.12.03","COMPLE_DATE":"2012.12.18"},{"IDX":137.0,"FAC_NM":"가든파이브웍스","ADDRESS":"충민로52(문정동)","TELEPHONE":"02-2047-1014","APPROVAL_DATE":"2008.11.12","COMPLE_DATE":"2008.10.16"},{"IDX":47.0,"FAC_NM":"STX-W 타워","ADDRESS":"구로동 615-3외 4필지","TELEPHONE":"6124-3333","APPROVAL_DATE":"2008.10.23","COMPLE_DATE":"2011.10.30"},{"IDX":192.0,"FAC_NM":"서울숲 코오롱\n디지털타워2차","ADDRESS":"성수동2가 333-140번지","TELEPHONE":"(031) 727-1461","APPROVAL_DATE":"2008.10.21","COMPLE_DATE":"2010.09.10"},{"IDX":110.0,"FAC_NM":"에이스하이엔드7차","ADDRESS":"가산동 345-33","TELEPHONE":"6111-1500","APPROVAL_DATE":"2008.10.10","COMPLE_DATE":"2010.07"},{"IDX":191.0,"FAC_NM":"서울숲 코오롱\n디지털타워3차","ADDRESS":"성수동1가 14-18번지 외 1 필지","TELEPHONE":"(02) 499-0430","APPROVAL_DATE":"2008.10.02","COMPLE_DATE":"2010.11.24"},{"IDX":69.0,"FAC_NM":"엘리시아","ADDRESS":"가산동 60-69","TELEPHONE":"890-8888","APPROVAL_DATE":"2008.09.23","COMPLE_DATE":"2011.03"},{"IDX":190.0,"FAC_NM":"휴먼테코","ADDRESS":"성수동2가 281-16 번지 외 1 필지","TELEPHONE":"02)6466-5000","APPROVAL_DATE":"2008.09.12","COMPLE_DATE":"2010.06.07"},{"IDX":112.0,"FAC_NM":"KCC웰츠밸리","ADDRESS":"가산동 470-8","TELEPHONE":"6111-8100","APPROVAL_DATE":"2008.09.09","COMPLE_DATE":"2010.12"},{"IDX":68.0,"FAC_NM":"대륭포스트타워6차","ADDRESS":"가산동 50-3","TELEPHONE":"2083-5114","APPROVAL_DATE":"2008.09.05","COMPLE_DATE":"2010.08"},{"IDX":189.0,"FAC_NM":"서울숲 \n한라시그마밸리","ADDRESS":"성수동2가 325-2 번지 외 12 필지","TELEPHONE":"(02) 6466-8114","APPROVAL_DATE":"2008.09.03","COMPLE_DATE":"2011.02.16"},{"IDX":111.0,"FAC_NM":"더루벤스밸리","ADDRESS":"가산동 691-3","TELEPHONE":"2109-9800","APPROVAL_DATE":"2008.08.14","COMPLE_DATE":"2011.09"},{"IDX":49.0,"FAC_NM":"파트너스타워2차","ADDRESS":"구로동 1128-3","TELEPHONE":"2028-3993","APPROVAL_DATE":"2008.07.28","COMPLE_DATE":"2010.02.16"},{"IDX":108.0,"FAC_NM":"STX V-TOWER","ADDRESS":"가산동 371-37","TELEPHONE":"8111-3102","APPROVAL_DATE":"2008.07","COMPLE_DATE":"2010.11"},{"IDX":188.0,"FAC_NM":"한신 아크밸리","ADDRESS":"성수동2가 277-43번지","TELEPHONE":"(02) 421-2367","APPROVAL_DATE":"2008.05.26","COMPLE_DATE":"2010.05.27"},{"IDX":158.0,"FAC_NM":"양평동이노플렉스","ADDRESS":"양산로57-5(양평동3가)","TELEPHONE":"2675-0134","APPROVAL_DATE":"2008.05.14","COMPLE_DATE":"2010.01.20"},{"IDX":67.0,"FAC_NM":"갑을아파트형공장","ADDRESS":"가산동60-5","TELEPHONE":"3397-7705","APPROVAL_DATE":"2008.05.09","COMPLE_DATE":"2010.07"},{"IDX":107.0,"FAC_NM":"IT프리미어타워","ADDRESS":"가산동 345-50","TELEPHONE":"2621-1991","APPROVAL_DATE":"2008.04.24","COMPLE_DATE":"2010.02"},{"IDX":106.0,"FAC_NM":"에이스하이엔드8차","ADDRESS":"가산동 345-4","TELEPHONE":"6123-5000","APPROVAL_DATE":"2008.03.20","COMPLE_DATE":"2010.09"},{"IDX":105.0,"FAC_NM":"BYC하이씨티","ADDRESS":"가산동 371-17","TELEPHONE":"6947-3100","APPROVAL_DATE":"2008.03.12","COMPLE_DATE":"2012.02"},{"IDX":104.0,"FAC_NM":"INNOPLEX 2차","ADDRESS":"가산동 371-59","TELEPHONE":"6111-0123","APPROVAL_DATE":"2008.02.20","COMPLE_DATE":"2010.03"},{"IDX":66.0,"FAC_NM":"대륭포스트타워5차","ADDRESS":"가산동 60-3","TELEPHONE":"2624-4116","APPROVAL_DATE":"2008.02.19","COMPLE_DATE":"2010.01"},{"IDX":103.0,"FAC_NM":"파트너스타워","ADDRESS":"가산동 345-13","TELEPHONE":"859-5641","APPROVAL_DATE":"2008.02.12","COMPLE_DATE":"2009.10"},{"IDX":102.0,"FAC_NM":"한라시그마밸리","ADDRESS":"가산동 345-90 ","TELEPHONE":"6343-6800","APPROVAL_DATE":"2008.01.17","COMPLE_DATE":"2009.12"},{"IDX":101.0,"FAC_NM":"백상스타타워2차","ADDRESS":"가산동 459-22","TELEPHONE":"6111-6100","APPROVAL_DATE":"2007.12.06","COMPLE_DATE":"2010.07"},{"IDX":65.0,"FAC_NM":"백상스타타워1차","ADDRESS":"가산동 60-17","TELEPHONE":"6111-7116","APPROVAL_DATE":"2007.11.29","COMPLE_DATE":"2010.07"},{"IDX":46.0,"FAC_NM":"한화비즈 메트로1차","ADDRESS":"구로동 851외 2필지","TELEPHONE":"2621-2490","APPROVAL_DATE":"2007.11.20","COMPLE_DATE":"2010.12.28"},{"IDX":211.0,"FAC_NM":"아시아미디어타워","ADDRESS":"초동 42","TELEPHONE":"2275-3332","APPROVAL_DATE":"2007.11.13","COMPLE_DATE":"2009.12.01"},{"IDX":99.0,"FAC_NM":"디지털엠파이어","ADDRESS":"가산동 685","TELEPHONE":"2624-2121","APPROVAL_DATE":"2007.10.17","COMPLE_DATE":"2009.02"},{"IDX":98.0,"FAC_NM":"LG아파트형공장","ADDRESS":"가산동 459-9","TELEPHONE":"6945-4455","APPROVAL_DATE":"2007.10.12","COMPLE_DATE":"2009.04"},{"IDX":154.0,"FAC_NM":"선유도우림라이온스밸리A","ADDRESS":"양평로 149(양평동5가)","TELEPHONE":"2638-7114","APPROVAL_DATE":"2007.09.17","COMPLE_DATE":"2009.08.07"},{"IDX":155.0,"FAC_NM":"선유도우림라이온스밸리B","ADDRESS":"양평로21가길19(양평동5가)","TELEPHONE":"2638-7114","APPROVAL_DATE":"2007.09.17","COMPLE_DATE":"2009.08.07"},{"IDX":64.0,"FAC_NM":"에이스하이엔드6차","ADDRESS":"가산동 60-25","TELEPHONE":"6299-5100","APPROVAL_DATE":"2007.08.24","COMPLE_DATE":"2009.08"},{"IDX":157.0,"FAC_NM":"벽산디지털밸리","ADDRESS":"경인로71길 70(문래동5가)","TELEPHONE":"6098-5114","APPROVAL_DATE":"2007.08.24","COMPLE_DATE":"2009.12.17"},{"IDX":97.0,"FAC_NM":"에이스하이엔드5차","ADDRESS":"가산동 505-18","TELEPHONE":"6340-0200","APPROVAL_DATE":"2007.08.23","COMPLE_DATE":"2009.07"},{"IDX":96.0,"FAC_NM":"이앤씨드림타워8차","ADDRESS":"가산동 327-27","TELEPHONE":"6277-8200","APPROVAL_DATE":"2007.08.16","COMPLE_DATE":"2009.02"},{"IDX":109.0,"FAC_NM":"가산비즈니스센터","ADDRESS":"가산동 371-6 ","TELEPHONE":"3289-9114","APPROVAL_DATE":"2007.08.16","COMPLE_DATE":"2011.09"},{"IDX":100.0,"FAC_NM":"한국전자협동APT공장","ADDRESS":"가산동 371-51","TELEPHONE":"858-9261","APPROVAL_DATE":"2007.08.13","COMPLE_DATE":"2007.12.06"},{"IDX":156.0,"FAC_NM":"금강펜테리움IT타워","ADDRESS":"당산로 171(당산동4가)","TELEPHONE":"2638-8585","APPROVAL_DATE":"2007.07.24","COMPLE_DATE":"2010.01.08"},{"IDX":44.0,"FAC_NM":"벽산디지털밸리7차","ADDRESS":"구로동 170-13","TELEPHONE":"839-3152","APPROVAL_DATE":"2007.07.23","COMPLE_DATE":"2009.06.23"},{"IDX":95.0,"FAC_NM":"에이스하이엔드3차","ADDRESS":"가산동 371-51","TELEPHONE":"2624-1100","APPROVAL_DATE":"2007.06.13","COMPLE_DATE":"2009.07"},{"IDX":86.0,"FAC_NM":"INNOPLEX 1차","ADDRESS":"가산동 371-47","TELEPHONE":"6679-0007","APPROVAL_DATE":"2007.04.13","COMPLE_DATE":"2008.08.14"},{"IDX":94.0,"FAC_NM":"벽산디지털밸리6차","ADDRESS":"가산동 481-4","TELEPHONE":"869-1166","APPROVAL_DATE":"2007.04.04","COMPLE_DATE":"2009.03"},{"IDX":187.0,"FAC_NM":"서울숲 코오롱 1차","ADDRESS":"성수동2가 308-4번지","TELEPHONE":"시행사:2115-8899","APPROVAL_DATE":"2007.02.11","COMPLE_DATE":"2010.06.10"},{"IDX":7.0,"FAC_NM":"우림블루나인비즈니스센터","ADDRESS":"양천로 583","TELEPHONE":"2093-1011","APPROVAL_DATE":"2006.4.26","COMPLE_DATE":"2008.9.26"},{"IDX":93.0,"FAC_NM":"롯데IT캐슬2차","ADDRESS":"가산동 371-16","TELEPHONE":"2627-8114","APPROVAL_DATE":"2006.11.21","COMPLE_DATE":"2008.09"},{"IDX":63.0,"FAC_NM":"이앤씨드림타워7차","ADDRESS":"가산동 60-44","TELEPHONE":"6277-8200","APPROVAL_DATE":"2006.11.06","COMPLE_DATE":"2008.01"},{"IDX":43.0,"FAC_NM":"에이스하이엔드타워2차","ADDRESS":"구로동 222-14","TELEPHONE":"6340-5555","APPROVAL_DATE":"2006.08.17","COMPLE_DATE":"2008.04.15"},{"IDX":186.0,"FAC_NM":"아주디지털타워","ADDRESS":"성수동2가 284-56번지","TELEPHONE":"(02) 462-2235","APPROVAL_DATE":"2006.07.27","COMPLE_DATE":"2010.01.08"},{"IDX":213.0,"FAC_NM":"산타플러스","ADDRESS":"난곡로 60","TELEPHONE":"02-865-6976","APPROVAL_DATE":"2005.11.28","COMPLE_DATE":"2006.7.26"},{"IDX":92.0,"FAC_NM":"㈜동광인터내셔날","ADDRESS":"가산동 459-14","TELEPHONE":"3479-2700","APPROVAL_DATE":"2005.11.23","COMPLE_DATE":"2006.01"},{"IDX":152.0,"FAC_NM":"월드메르디앙비즈센터","ADDRESS":"양산로 53(양평동3가)","TELEPHONE":"2165-8980","APPROVAL_DATE":"2005.10.05","COMPLE_DATE":"2007.02.14"},{"IDX":61.0,"FAC_NM":"(주)한섬임대아파트형공장","ADDRESS":"가산동 60-42","TELEPHONE":"838-0146","APPROVAL_DATE":"2005.09.28","COMPLE_DATE":"2006.09"},{"IDX":41.0,"FAC_NM":"㈜대양디앤티","ADDRESS":"구로동 197-47","TELEPHONE":"858-2111","APPROVAL_DATE":"2005.09.09","COMPLE_DATE":"2007.08.07"},{"IDX":91.0,"FAC_NM":"승일벤쳐타워","ADDRESS":"가산동 371-42","TELEPHONE":"862-2351","APPROVAL_DATE":"2005.06.18","COMPLE_DATE":"2006.12"},{"IDX":42.0,"FAC_NM":"대륭포스트타워3차","ADDRESS":"구로동 182-4","TELEPHONE":"2028-0114","APPROVAL_DATE":"2005.06.10","COMPLE_DATE":"2007.06.07"},{"IDX":153.0,"FAC_NM":"에이스하이테크시티","ADDRESS":"경인로 775(문래동3가)","TELEPHONE":"6309-6112","APPROVAL_DATE":"2005.05.15","COMPLE_DATE":"2007.04.13"},{"IDX":90.0,"FAC_NM":"롯데정보통신","ADDRESS":"가산동 533-2","TELEPHONE":"2626-4000","APPROVAL_DATE":"2005.05.11","COMPLE_DATE":"2007.03"},{"IDX":134.0,"FAC_NM":"DMC 첨단산업센터","ADDRESS":"마포구 상암동 1580 \n첨단산업센터","TELEPHONE":"2171-2847","APPROVAL_DATE":"2004.11.03","COMPLE_DATE":"2008.03.31"},{"IDX":62.0,"FAC_NM":"IT미래타워","ADDRESS":"가산동 60-21","TELEPHONE":"2027-5757","APPROVAL_DATE":"2004.10.27","COMPLE_DATE":"2007.04.30"},{"IDX":89.0,"FAC_NM":"뉴티캐슬","ADDRESS":"가산동 429-1","TELEPHONE":"2626-9960","APPROVAL_DATE":"2004.08.11","COMPLE_DATE":"2006.12"},{"IDX":88.0,"FAC_NM":"대륭테크노타운13차","ADDRESS":"가산동 664","TELEPHONE":"2029-5600","APPROVAL_DATE":"2004.07.28","COMPLE_DATE":"2008.05"},{"IDX":185.0,"FAC_NM":"성수동\n 우림e-BIZ Center","ADDRESS":"성수동2가 280-21번지","TELEPHONE":"(02)2024-2110","APPROVAL_DATE":"2004.07.26","COMPLE_DATE":"2006.10.18"},{"IDX":132.0,"FAC_NM":"중계제1공단","ADDRESS":"노원구 노원로19길 31(중계동)\n[중계동 511-2]","TELEPHONE":"948-2846","APPROVAL_DATE":"2004.07.13","COMPLE_DATE":"1991.12.07"},{"IDX":130.0,"FAC_NM":"월계테크노타운","ADDRESS":"노원구 월계로45길 28(월계동)\n[월계동 562번지]","TELEPHONE":"990-2727","APPROVAL_DATE":"2004.07.08","COMPLE_DATE":"1994.12.19"},{"IDX":87.0,"FAC_NM":"대륭테크노타운12차","ADDRESS":"가산동 327-32","TELEPHONE":"2029-6114","APPROVAL_DATE":"2004.07.08","COMPLE_DATE":"2008.05"},{"IDX":131.0,"FAC_NM":"하계테크노타운","ADDRESS":"노원구 노원로15길 10(하계동)\n[하계동 250-3]","TELEPHONE":"6235-3500","APPROVAL_DATE":"2004.07.07","COMPLE_DATE":"1998.11.17"},{"IDX":184.0,"FAC_NM":"풍림테크원","ADDRESS":"성수동2가 273-10번지","TELEPHONE":"(02) 468-9319/464-0133","APPROVAL_DATE":"2004.05.31","COMPLE_DATE":"2005.09.15"},{"IDX":31.0,"FAC_NM":"이앤씨드림타워6차","ADDRESS":"구로동 197-28","TELEPHONE":"801-8603","APPROVAL_DATE":"2004.05.10","COMPLE_DATE":"2005.12.21"},{"IDX":39.0,"FAC_NM":"대륭포스트타워2차","ADDRESS":"구로동 182-13","TELEPHONE":"2082-0114","APPROVAL_DATE":"2004.03.24","COMPLE_DATE":"2005.10.06"},{"IDX":60.0,"FAC_NM":"스타밸리","ADDRESS":"가산동 60-11","TELEPHONE":"2027-0114","APPROVAL_DATE":"2004.02.27","COMPLE_DATE":"2006.04"},{"IDX":37.0,"FAC_NM":"코오롱빌란트2차","ADDRESS":"구로동 222-8","TELEPHONE":"2081-1111","APPROVAL_DATE":"2004.02.25","COMPLE_DATE":"2006.12.28"},{"IDX":38.0,"FAC_NM":"대륭포스트타워1차","ADDRESS":"구로동 212-8","TELEPHONE":"2082-2331","APPROVAL_DATE":"2004.01.10","COMPLE_DATE":"2005.10.18"},{"IDX":36.0,"FAC_NM":"코오롱싸이언스밸리2차","ADDRESS":"구로동 811","TELEPHONE":"850-3150","APPROVAL_DATE":"2003.12.30","COMPLE_DATE":"2005.12.13"},{"IDX":34.0,"FAC_NM":"에이스하이엔드1차","ADDRESS":"구로동 235-2","TELEPHONE":"6220-2010","APPROVAL_DATE":"2003.12.30","COMPLE_DATE":"2005.09.30"},{"IDX":150.0,"FAC_NM":"메가벤처타워","ADDRESS":"문래로20길60(문래동3가)","TELEPHONE":"2632-4438","APPROVAL_DATE":"2003.12.22","COMPLE_DATE":"2005.12.27"},{"IDX":79.0,"FAC_NM":"롯데IT캐슬","ADDRESS":"가산동 550-1","TELEPHONE":"2026-8970","APPROVAL_DATE":"2003.12.20","COMPLE_DATE":"2005.09"},{"IDX":30.0,"FAC_NM":"이앤씨드림타워5차","ADDRESS":"구로동 197-13","TELEPHONE":"6336-3591","APPROVAL_DATE":"2003.12.19","COMPLE_DATE":"2004.12.14"},{"IDX":59.0,"FAC_NM":"벽산디지털밸리5차","ADDRESS":"가산동 60-73","TELEPHONE":"2082-5990","APPROVAL_DATE":"2003.11.05","COMPLE_DATE":"2005.10"},{"IDX":33.0,"FAC_NM":"마리오디지털밸리","ADDRESS":"구로동 222-12","TELEPHONE":"890-8498","APPROVAL_DATE":"2003.10.13","COMPLE_DATE":"2005.10.25"},{"IDX":85.0,"FAC_NM":"코오롱디지털타워애스톤","ADDRESS":"가산동 505-14","TELEPHONE":"2082-8114","APPROVAL_DATE":"2003.09.26","COMPLE_DATE":"2005.09"},{"IDX":84.0,"FAC_NM":"에이스테크노타워10차","ADDRESS":"가산동 470-5","TELEPHONE":"6670-5300","APPROVAL_DATE":"2003.09.16","COMPLE_DATE":"2005.07"},{"IDX":35.0,"FAC_NM":"코오롱싸이언스밸리1차","ADDRESS":"구로동 187-10","TELEPHONE":"2025-4580","APPROVAL_DATE":"2003.08.08","COMPLE_DATE":"2005.07.05"},{"IDX":40.0,"FAC_NM":"삼성IT밸리","ADDRESS":"구로동 197-5","TELEPHONE":"2028-2363","APPROVAL_DATE":"2003.07.20","COMPLE_DATE":"2007.03.30"},{"IDX":149.0,"FAC_NM":"문래동빅토리테크노타워","ADDRESS":"선유서로 17(문래동5가)","TELEPHONE":"2068-8212","APPROVAL_DATE":"2003.07.08","COMPLE_DATE":"2004.10.08"},{"IDX":183.0,"FAC_NM":"(주)삼우","ADDRESS":"성수동2가 272-38번지","TELEPHONE":"(02) 2274-2734","APPROVAL_DATE":"2003.06.30","COMPLE_DATE":"2003.12.17"},{"IDX":83.0,"FAC_NM":"에이스테크노타워9차","ADDRESS":"가산동 345-30","TELEPHONE":"2026-1900","APPROVAL_DATE":"2003.06.30","COMPLE_DATE":"2005.07"},{"IDX":181.0,"FAC_NM":"영동테크노타워","ADDRESS":"성수동2가 300-4번지","TELEPHONE":"(02) 2118-7012","APPROVAL_DATE":"2003.06.20","COMPLE_DATE":"2003.06.20"},{"IDX":182.0,"FAC_NM":"삼환디지털\n벤처타워","ADDRESS":"성수동2가 280-13번지","TELEPHONE":"2024-0020(관리실)","APPROVAL_DATE":"2003.06.20","COMPLE_DATE":"2006.01.19"},{"IDX":82.0,"FAC_NM":"제이플라츠","ADDRESS":"가산동 459-11 ","TELEPHONE":"2028-5000","APPROVAL_DATE":"2003.06.20","COMPLE_DATE":"2007.04"},{"IDX":29.0,"FAC_NM":"이앤씨드림타워3차","ADDRESS":"구로동 197-33","TELEPHONE":"6330-2302","APPROVAL_DATE":"2003.06.13","COMPLE_DATE":"2004.09.08"},{"IDX":81.0,"FAC_NM":"우림라이온스밸리2차","ADDRESS":"가산동 680","TELEPHONE":"2027-2114","APPROVAL_DATE":"2003.05.28","COMPLE_DATE":"2006.05"},{"IDX":28.0,"FAC_NM":"이앤씨드림타워2차","ADDRESS":"구로동 197-10","TELEPHONE":"6330-2200","APPROVAL_DATE":"2003.05.07","COMPLE_DATE":"2004.09.08"},{"IDX":80.0,"FAC_NM":"호서대벤처타워","ADDRESS":"가산동 319","TELEPHONE":"2627-5980","APPROVAL_DATE":"2003.04.24.","COMPLE_DATE":"2008.10.07"},{"IDX":58.0,"FAC_NM":"SJ테크노빌","ADDRESS":"가산동 60-19","

In [147]:
data = response.json()
rows = data['InfoBizcenterApply']['row']
print(rows)

center_df = pd.DataFrame(rows)
center_df

[{'IDX': 208.0, 'FAC_NM': '신내테크노타운', 'ADDRESS': '봉화산로 123(상봉동)', 'TELEPHONE': '02)3423-0057', 'APPROVAL_DATE': '96.5.28', 'COMPLE_DATE': '99.10.18'}, {'IDX': 136.0, 'FAC_NM': '월곡동아파트형공장', 'ADDRESS': '하월곡동 96-113', 'TELEPHONE': '02-090-8083', 'APPROVAL_DATE': '33289', 'COMPLE_DATE': '1990.12.31'}, {'IDX': 135.0, 'FAC_NM': '월곡동아파트형공장', 'ADDRESS': '하월곡동 96-113', 'TELEPHONE': '02-912-1034', 'APPROVAL_DATE': '33289', 'COMPLE_DATE': '1990.12.31'}, {'IDX': 140.0, 'FAC_NM': '문정아르페온 1차 지식산업센터', 'ADDRESS': '서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)', 'TELEPHONE': '031-706-8577', 'APPROVAL_DATE': '2016.06.27', 'COMPLE_DATE': '2016.06.27'}, {'IDX': 139.0, 'FAC_NM': '문정 대명벨리온', 'ADDRESS': '서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)', 'TELEPHONE': '02-2222-7357', 'APPROVAL_DATE': '2016.03.23', 'COMPLE_DATE': '2016.03.23'}, {'IDX': 141.0, 'FAC_NM': '문정 현대지식산업센터Ｉ-1', 'ADDRESS': '서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)', 'TELEPHONE': '02-3451-0100', 'APPROVAL_DATE': '2016.02.29', 'COMPLE_DATE': '2016.02.29'}, {'IDX': 138.0, 'FAC_NM': '송파유탑테크밸리', 'ADDRESS': '서울특별시 송파구 문정동 651-14 (문정도시개발구역 3-12BL)', 'TELEPHONE': '062-526-8383', 'APPROVAL_DATE': '2015.12.18', 'COMPLE_DATE': '2015.12.18'}, {'IDX': 207.0, 'FAC_NM': '포휴', 'ADDRESS': '성수동1가 656-3', 'TELEPHONE': '3416-1500', 'APPROVAL_DATE': '2013.08.30', 'COMPLE_DATE': '2016.5.3'}, {'IDX': 117.0, 'FAC_NM': '에이스하이엔드타워 10차', 'ADDRESS': '가산동 660', 'TELEPHONE': '6309-6045', 'APPROVAL_DATE': '2013.08.29', 'COMPLE_DATE': '2015.10.28'}, {'IDX': 206.0, 'FAC_NM': 'BY센터', 'ADDRESS': '성수동2가 301-51,301-38', 'TELEPHONE': '(02) 467-2247', 'APPROVAL_DATE': '2013.08.12', 'COMPLE_DATE': '2015.12.04'}, {'IDX': 205.0, 'FAC_NM': '신한IT타워', 'ADDRESS': '성수동1가 656-603', 'TELEPHONE': '', 'APPROVAL_DATE': '2013.07.02', 'COMPLE_DATE': '2015.06.04'}, {'IDX': 116.0, 'FAC_NM': '에스비즈니스센터', 'ADDRESS': '가산동 343-8', 'TELEPHONE': '2163-6749', 'APPROVAL_DATE': '2013.03.26', 'COMPLE_DATE': '2015.06.01'}, {'IDX': 165.0, 'FAC_NM': '선유도역2차 아이에스비즈타워', 'ADDRESS': '선유로49길 23(양평동4가)', 'TELEPHONE': '6123-4100', 'APPROVAL_DATE': '2012.12.18', 'COMPLE_DATE': '2014.11.19'}, {'IDX': 115.0, 'FAC_NM': '대륭테크노타운17차', 'ADDRESS': '가산동 670', 'TELEPHONE': '3466-0051', 'APPROVAL_DATE': '2012.12.10', 'COMPLE_DATE': '2015.05.15'}, {'IDX': 204.0, 'FAC_NM': '서울숲\n드림타워(삼공)', 'ADDRESS': '성수동2가 323, 309-51', 'TELEPHONE': '(02)6222-8114', 'APPROVAL_DATE': '2012.10.31', 'COMPLE_DATE': '2015.03.23'}, {'IDX': 164.0, 'FAC_NM': '에이스하이테크시티 2', 'ADDRESS': '선유로13길 25(문래동6가)', 'TELEPHONE': '2257-8114', 'APPROVAL_DATE': '2012.08.27', 'COMPLE_DATE': '2014.10.24'}, {'IDX': 2.0, 'FAC_NM': 'NICE그룹 지식산업센터', 'ADDRESS': '상일로6길 55 (상일동)', 'TELEPHONE': '2122-4415', 'APPROVAL_DATE': '2012.06.29', 'COMPLE_DATE': '2014.02.28'}, {'IDX': 166.0, 'FAC_NM': 'SK V1 center', 'ADDRESS': '당산로41길 11(당산동4가)', 'TELEPHONE': '6121-8100', 'APPROVAL_DATE': '2012.06.19', 'COMPLE_DATE': '2015.02.17'}, {'IDX': 203.0, 'FAC_NM': '서울숲IT캐슬', 'ADDRESS': '성수동1가 671-6, -41 외 4필지', 'TELEPHONE': '(02) 2086-3346', 'APPROVAL_DATE': '2012.05.10', 'COMPLE_DATE': '2014.06.17'}, {'IDX': 1.0, 'FAC_NM': '세종투자㈜', 'ADDRESS': '강동구 상일로10길 36 (상일동)', 'TELEPHONE': '3415-4971', 'APPROVAL_DATE': '2011.11.30', 'COMPLE_DATE': '2013.09.13'}, {'IDX': 202.0, 'FAC_NM': '에이스하이앤드\n 성수타워', 'ADDRESS': '성수동2가 269-25,269-51,\n269-115,328-5', 'TELEPHONE': '(02) 2112-6491', 'APPROVAL_DATE': '2011.11.15', 'COMPLE_DATE': '2015.06.19'}, {'IDX': 201.0, 'FAC_NM': '에이스성수타워1차', 'ADDRESS': '성수2가 280-15,19', 'TELEPHONE': '(02) 591-0607', 'APPROVAL_DATE': '2011.10.20', 'COMPLE_DATE': '2014.03.11'}, {'IDX': 52.0, 'FAC_NM': 'G플러스 코오롱 디지털타워', 'ADDRESS': '구로동 222-31', 'TELEPHONE': '858-3650', 'APPROVAL_DATE': '2011.06.09', 'COMPLE_DATE': '2013.7.24'}, {'IDX': 163.0, 'FAC_NM': '선유도역1차 아이에스비즈타워', 'ADDRESS': '양평로21길 26(양평동5가)', 'TELEPHONE': '6968-1004', 'APPROVAL_DATE': '2011.04.21', 'COMPLE_DATE': '2013.5.27'}, {'IDX': 200.0, 'FAC_NM': '서울숲\n한라시그마밸리II', 'ADDRESS': '성수동2가 333-15', 'TELEPHONE': '(02) 4199-5621', 'APPROVAL_DATE': '2011.02.25', 'COMPLE_DATE': '2013.03.28'}, {'IDX': 51.0, 'FAC_NM': '대륭포스트타워7차', 'ADDRESS': '구로동 170-10 외 2필지', 'TELEPHONE': '6942-9500', 'APPROVAL_DATE': '2011.02.21', 'COMPLE_DATE': '2012.12.11'}, {'IDX': 10.0, 'FAC_NM': '강서IT밸리', 'ADDRESS': '화곡로68길 82', 'TELEPHONE': '6961-5111', 'APPROVAL_DATE': '2010.3.9', 'COMPLE_DATE': '2012.2.6'}, {'IDX': 11.0, 'FAC_NM': '강서한강자이', 'ADDRESS': '양천로 401', 'TELEPHONE': '6968-5801~2', 'APPROVAL_DATE': '2010.10.15', 'COMPLE_DATE': '2013.6.7'}, {'IDX': 199.0, 'FAC_NM': '서울숲 \n한라에코벨리', 'ADDRESS': '성수동1가 656-36\n656-1222', 'TELEPHONE': '(02) 549-6693', 'APPROVAL_DATE': '2010.09.09', 'COMPLE_DATE': '2012.09.06'}, {'IDX': 198.0, 'FAC_NM': '성수동\n아이에스비즈타워', 'ADDRESS': '성수동2가289-319,327,328', 'TELEPHONE': '(02) 3218-6643', 'APPROVAL_DATE': '2010.08.28', 'COMPLE_DATE': '2012.07.23'}, {'IDX': 162.0, 'FAC_NM': 'KnK디지털타워', 'ADDRESS': '영신로 220(영등포동8가)', 'TELEPHONE': '2675-6060', 'APPROVAL_DATE': '2010.08.27', 'COMPLE_DATE': '2012.12.07'}, {'IDX': 167.0, 'FAC_NM': '문래동 하우스디 비즈', 'ADDRESS': '선유로3길 10(문래동5가)', 'TELEPHONE': '2112-6339', 'APPROVAL_DATE': '2010.08.10', 'COMPLE_DATE': '2016.05.09'}, {'IDX': 160.0, 'FAC_NM': '선유도코오롱디지털타워', 'ADDRESS': '양평로22길21(양평동5가)', 'TELEPHONE': '2062-5996', 'APPROVAL_DATE': '2010.07.13', 'COMPLE_DATE': '2012.03.23'}, {'IDX': 197.0, 'FAC_NM': '성수에이팩센터', 'ADDRESS': '성수동2가 289-5\n289-334,289-335', 'TELEPHONE': '(02) 3416-1541', 'APPROVAL_DATE': '2010.06.24', 'COMPLE_DATE': '2012.08.24'}, {'IDX': 196.0, 'FAC_NM': '아연디지털타워', 'ADDRESS': '성수동2가314-37', 'TELEPHONE': '(02) 499-2275', 'APPROVAL_DATE': '2010.06.01', 'COMPLE_DATE': '2012.08.31'}, {'IDX': 195.0, 'FAC_NM': '서울숲 SK V1 타워', 'ADDRESS': '성수동2가284-55, 284-107', 'TELEPHONE': '(02) 6233-8000', 'APPROVAL_DATE': '2010.04.13', 'COMPLE_DATE': '2014.07.18'}, {'IDX': 114.0, 'FAC_NM': '에이스하이엔드9차', 'ADDRESS': '가산동 481-2', 'TELEPHONE': '6309-6051', 'APPROVAL_DATE': '2010.04', 'COMPLE_DATE': '2012.07.20'}, {'IDX': 194.0, 'FAC_NM': '서울숲\nIT 밸리', 'ADDRESS': '성수동1가 13-170\n외9필지(13-170,13-166,13-472,13-169,13-256,13-164,13-253,13-171,13-255,13-167)', 'TELEPHONE': '(02) 2090-8202', 'APPROVAL_DATE': '2010.03.24.', 'COMPLE_DATE': '2013.02.08'}, {'IDX': 50.0, 'FAC_NM': 'JnK 디지털타워', 'ADDRESS': '구로3동 222-3', 'TELEPHONE': '6124-6611', 'APPROVAL_DATE': '2010.01.20', 'COMPLE_DATE': '2012.2.15'}, {'IDX': 121.0, 'FAC_NM': '대성D-POLIS', 'ADDRESS': '가산동 543-1', 'TELEPHONE': '861-9114', 'APPROVAL_DATE': '2009.12', 'COMPLE_DATE': '2012.09'}, {'IDX': 159.0, 'FAC_NM': '동아프라임밸리', 'ADDRESS': '영등포로5길19(양평동2가)', 'TELEPHONE': '6210-7201', 'APPROVAL_DATE': '2009.10.21', 'COMPLE_DATE': '2011.11.25'}, {'IDX': 161.0, 'FAC_NM': '솔버스 비즈타워', 'ADDRESS': '선유서로31길3(양평동3가)', 'TELEPHONE': '6963-8080', 'APPROVAL_DATE': '2009.10.19', 'COMPLE_DATE': '2012.09.05'}, {'IDX': 212.0, 'FAC_NM': '동대문패션비즈센터 ', 'ADDRESS': '신당동 251-160', 'TELEPHONE': '070-8895-7347', 'APPROVAL_DATE': '2009.05.14', 'COMPLE_DATE': '2012.03.07'}, {'IDX': 129.0, 'FAC_NM': '현대지식산업센터', 'ADDRESS': '독산동 291-1 ', 'TELEPHONE': '858-3080', 'APPROVAL_DATE': '2009.04', 'COMPLE_DATE': '2014.03.04'}, {'IDX': 193.0, 'FAC_NM': '이레타워', 'ADDRESS': '성수동2가 277-175번지', 'TELEPHONE': '(02) 466-2663', 'APPROVAL_DATE': '2009.01.22', 'COMPLE_DATE': '2009.08.07'}, {'IDX': 9.0, 'FAC_NM': '강서한화비즈메트로2차', 'ADDRESS': '양천로551-24', 'TELEPHONE': '6957-1990', 'APPROVAL_DATE': '2008.7.25', 'COMPLE_DATE': '2012.1.16'}, {'IDX': 8.0, 'FAC_NM': '강서한화비즈메트로1차', 'ADDRESS': '양천로551-17', 'TELEPHONE': '6957-1990', 'APPROVAL_DATE': '2008.7.25', 'COMPLE_DATE': '2012.1.13'}, {'IDX': 113.0, 'FAC_NM': '알에스엠타워', 'ADDRESS': '가산동 327-29', 'TELEPHONE': '2112-6300', 'APPROVAL_DATE': '2008.12.03', 'COMPLE_DATE': '2012.12.18'}, {'IDX': 137.0, 'FAC_NM': '가든파이브웍스', 'ADDRESS': '충민로52(문정동)', 'TELEPHONE': '02-2047-1014', 'APPROVAL_DATE': '2008.11.12', 'COMPLE_DATE': '2008.10.16'}, {'IDX': 47.0, 'FAC_NM': 'STX-W 타워', 'ADDRESS': '구로동 615-3외 4필지', 'TELEPHONE': '6124-3333', 'APPROVAL_DATE': '2008.10.23', 'COMPLE_DATE': '2011.10.30'}, {'IDX': 192.0, 'FAC_NM': '서울숲 코오롱\n디지털타워2차', 'ADDRESS': '성수동2가 333-140번지', 'TELEPHONE': '(031) 727-1461', 'APPROVAL_DATE': '2008.10.21', 'COMPLE_DATE': '2010.09.10'}, {'IDX': 110.0, 'FAC_NM': '에이스하이엔드7차', 'ADDRESS': '가산동 345-33', 'TELEPHONE': '6111-1500', 'APPROVAL_DATE': '2008.10.10', 'COMPLE_DATE': '2010.07'}, {'IDX': 191.0, 'FAC_NM': '서울숲 코오롱\n디지털타워3차', 'ADDRESS': '성수동1가 14-18번지 외 1 필지', 'TELEPHONE': '(02) 499-0430', 'APPROVAL_DATE': '2008.10.02', 'COMPLE_DATE': '2010.11.24'}, {'IDX': 69.0, 'FAC_NM': '엘리시아', 'ADDRESS': '가산동 60-69', 'TELEPHONE': '890-8888', 'APPROVAL_DATE': '2008.09.23', 'COMPLE_DATE': '2011.03'}, {'IDX': 190.0, 'FAC_NM': '휴먼테코', 'ADDRESS': '성수동2가 281-16 번지 외 1 필지', 'TELEPHONE': '02)6466-5000', 'APPROVAL_DATE': '2008.09.12', 'COMPLE_DATE': '2010.06.07'}, {'IDX': 112.0, 'FAC_NM': 'KCC웰츠밸리', 'ADDRESS': '가산동 470-8', 'TELEPHONE': '6111-8100', 'APPROVAL_DATE': '2008.09.09', 'COMPLE_DATE': '2010.12'}, {'IDX': 68.0, 'FAC_NM': '대륭포스트타워6차', 'ADDRESS': '가산동 50-3', 'TELEPHONE': '2083-5114', 'APPROVAL_DATE': '2008.09.05', 'COMPLE_DATE': '2010.08'}, {'IDX': 189.0, 'FAC_NM': '서울숲 \n한라시그마밸리', 'ADDRESS': '성수동2가 325-2 번지 외 12 필지', 'TELEPHONE': '(02) 6466-8114', 'APPROVAL_DATE': '2008.09.03', 'COMPLE_DATE': '2011.02.16'}, {'IDX': 111.0, 'FAC_NM': '더루벤스밸리', 'ADDRESS': '가산동 691-3', 'TELEPHONE': '2109-9800', 'APPROVAL_DATE': '2008.08.14', 'COMPLE_DATE': '2011.09'}, {'IDX': 49.0, 'FAC_NM': '파트너스타워2차', 'ADDRESS': '구로동 1128-3', 'TELEPHONE': '2028-3993', 'APPROVAL_DATE': '2008.07.28', 'COMPLE_DATE': '2010.02.16'}, {'IDX': 108.0, 'FAC_NM': 'STX V-TOWER', 'ADDRESS': '가산동 371-37', 'TELEPHONE': '8111-3102', 'APPROVAL_DATE': '2008.07', 'COMPLE_DATE': '2010.11'}, {'IDX': 188.0, 'FAC_NM': '한신 아크밸리', 'ADDRESS': '성수동2가 277-43번지', 'TELEPHONE': '(02) 421-2367', 'APPROVAL_DATE': '2008.05.26', 'COMPLE_DATE': '2010.05.27'}, {'IDX': 158.0, 'FAC_NM': '양평동이노플렉스', 'ADDRESS': '양산로57-5(양평동3가)', 'TELEPHONE': '2675-0134', 'APPROVAL_DATE': '2008.05.14', 'COMPLE_DATE': '2010.01.20'}, {'IDX': 67.0, 'FAC_NM': '갑을아파트형공장', 'ADDRESS': '가산동60-5', 'TELEPHONE': '3397-7705', 'APPROVAL_DATE': '2008.05.09', 'COMPLE_DATE': '2010.07'}, {'IDX': 107.0, 'FAC_NM': 'IT프리미어타워', 'ADDRESS': '가산동 345-50', 'TELEPHONE': '2621-1991', 'APPROVAL_DATE': '2008.04.24', 'COMPLE_DATE': '2010.02'}, {'IDX': 106.0, 'FAC_NM': '에이스하이엔드8차', 'ADDRESS': '가산동 345-4', 'TELEPHONE': '6123-5000', 'APPROVAL_DATE': '2008.03.20', 'COMPLE_DATE': '2010.09'}, {'IDX': 105.0, 'FAC_NM': 'BYC하이씨티', 'ADDRESS': '가산동 371-17', 'TELEPHONE': '6947-3100', 'APPROVAL_DATE': '2008.03.12', 'COMPLE_DATE': '2012.02'}, {'IDX': 104.0, 'FAC_NM': 'INNOPLEX 2차', 'ADDRESS': '가산동 371-59', 'TELEPHONE': '6111-0123', 'APPROVAL_DATE': '2008.02.20', 'COMPLE_DATE': '2010.03'}, {'IDX': 66.0, 'FAC_NM': '대륭포스트타워5차', 'ADDRESS': '가산동 60-3', 'TELEPHONE': '2624-4116', 'APPROVAL_DATE': '2008.02.19', 'COMPLE_DATE': '2010.01'}, {'IDX': 103.0, 'FAC_NM': '파트너스타워', 'ADDRESS': '가산동 345-13', 'TELEPHONE': '859-5641', 'APPROVAL_DATE': '2008.02.12', 'COMPLE_DATE': '2009.10'}, {'IDX': 102.0, 'FAC_NM': '한라시그마밸리', 'ADDRESS': '가산동 345-90 ', 'TELEPHONE': '6343-6800', 'APPROVAL_DATE': '2008.01.17', 'COMPLE_DATE': '2009.12'}, {'IDX': 101.0, 'FAC_NM': '백상스타타워2차', 'ADDRESS': '가산동 459-22', 'TELEPHONE': '6111-6100', 'APPROVAL_DATE': '2007.12.06', 'COMPLE_DATE': '2010.07'}, {'IDX': 65.0, 'FAC_NM': '백상스타타워1차', 'ADDRESS': '가산동 60-17', 'TELEPHONE': '6111-7116', 'APPROVAL_DATE': '2007.11.29', 'COMPLE_DATE': '2010.07'}, {'IDX': 46.0, 'FAC_NM': '한화비즈 메트로1차', 'ADDRESS': '구로동 851외 2필지', 'TELEPHONE': '2621-2490', 'APPROVAL_DATE': '2007.11.20', 'COMPLE_DATE': '2010.12.28'}, {'IDX': 211.0, 'FAC_NM': '아시아미디어타워', 'ADDRESS': '초동 42', 'TELEPHONE': '2275-3332', 'APPROVAL_DATE': '2007.11.13', 'COMPLE_DATE': '2009.12.01'}, {'IDX': 99.0, 'FAC_NM': '디지털엠파이어', 'ADDRESS': '가산동 685', 'TELEPHONE': '2624-2121', 'APPROVAL_DATE': '2007.10.17', 'COMPLE_DATE': '2009.02'}, {'IDX': 98.0, 'FAC_NM': 'LG아파트형공장', 'ADDRESS': '가산동 459-9', 'TELEPHONE': '6945-4455', 'APPROVAL_DATE': '2007.10.12', 'COMPLE_DATE': '2009.04'}, {'IDX': 154.0, 'FAC_NM': '선유도우림라이온스밸리A', 'ADDRESS': '양평로 149(양평동5가)', 'TELEPHONE': '2638-7114', 'APPROVAL_DATE': '2007.09.17', 'COMPLE_DATE': '2009.08.07'}, {'IDX': 155.0, 'FAC_NM': '선유도우림라이온스밸리B', 'ADDRESS': '양평로21가길19(양평동5가)', 'TELEPHONE': '2638-7114', 'APPROVAL_DATE': '2007.09.17', 'COMPLE_DATE': '2009.08.07'}, {'IDX': 64.0, 'FAC_NM': '에이스하이엔드6차', 'ADDRESS': '가산동 60-25', 'TELEPHONE': '6299-5100', 'APPROVAL_DATE': '2007.08.24', 'COMPLE_DATE': '2009.08'}, {'IDX': 157.0, 'FAC_NM': '벽산디지털밸리', 'ADDRESS': '경인로71길 70(문래동5가)', 'TELEPHONE': '6098-5114', 'APPROVAL_DATE': '2007.08.24', 'COMPLE_DATE': '2009.12.17'}, {'IDX': 97.0, 'FAC_NM': '에이스하이엔드5차', 'ADDRESS': '가산동 505-18', 'TELEPHONE': '6340-0200', 'APPROVAL_DATE': '2007.08.23', 'COMPLE_DATE': '2009.07'}, {'IDX': 96.0, 'FAC_NM': '이앤씨드림타워8차', 'ADDRESS': '가산동 327-27', 'TELEPHONE': '6277-8200', 'APPROVAL_DATE': '2007.08.16', 'COMPLE_DATE': '2009.02'}, {'IDX': 109.0, 'FAC_NM': '가산비즈니스센터', 'ADDRESS': '가산동 371-6 ', 'TELEPHONE': '3289-9114', 'APPROVAL_DATE': '2007.08.16', 'COMPLE_DATE': '2011.09'}, {'IDX': 100.0, 'FAC_NM': '한국전자협동APT공장', 'ADDRESS': '가산동 371-51', 'TELEPHONE': '858-9261', 'APPROVAL_DATE': '2007.08.13', 'COMPLE_DATE': '2007.12.06'}, {'IDX': 156.0, 'FAC_NM': '금강펜테리움IT타워', 'ADDRESS': '당산로 171(당산동4가)', 'TELEPHONE': '2638-8585', 'APPROVAL_DATE': '2007.07.24', 'COMPLE_DATE': '2010.01.08'}, {'IDX': 44.0, 'FAC_NM': '벽산디지털밸리7차', 'ADDRESS': '구로동 170-13', 'TELEPHONE': '839-3152', 'APPROVAL_DATE': '2007.07.23', 'COMPLE_DATE': '2009.06.23'}, {'IDX': 95.0, 'FAC_NM': '에이스하이엔드3차', 'ADDRESS': '가산동 371-51', 'TELEPHONE': '2624-1100', 'APPROVAL_DATE': '2007.06.13', 'COMPLE_DATE': '2009.07'}, {'IDX': 86.0, 'FAC_NM': 'INNOPLEX 1차', 'ADDRESS': '가산동 371-47', 'TELEPHONE': '6679-0007', 'APPROVAL_DATE': '2007.04.13', 'COMPLE_DATE': '2008.08.14'}, {'IDX': 94.0, 'FAC_NM': '벽산디지털밸리6차', 'ADDRESS': '가산동 481-4', 'TELEPHONE': '869-1166', 'APPROVAL_DATE': '2007.04.04', 'COMPLE_DATE': '2009.03'}, {'IDX': 187.0, 'FAC_NM': '서울숲 코오롱 1차', 'ADDRESS': '성수동2가 308-4번지', 'TELEPHONE': '시행사:2115-8899', 'APPROVAL_DATE': '2007.02.11', 'COMPLE_DATE': '2010.06.10'}, {'IDX': 7.0, 'FAC_NM': '우림블루나인비즈니스센터', 'ADDRESS': '양천로 583', 'TELEPHONE': '2093-1011', 'APPROVAL_DATE': '2006.4.26', 'COMPLE_DATE': '2008.9.26'}, {'IDX': 93.0, 'FAC_NM': '롯데IT캐슬2차', 'ADDRESS': '가산동 371-16', 'TELEPHONE': '2627-8114', 'APPROVAL_DATE': '2006.11.21', 'COMPLE_DATE': '2008.09'}, {'IDX': 63.0, 'FAC_NM': '이앤씨드림타워7차', 'ADDRESS': '가산동 60-44', 'TELEPHONE': '6277-8200', 'APPROVAL_DATE': '2006.11.06', 'COMPLE_DATE': '2008.01'}, {'IDX': 43.0, 'FAC_NM': '에이스하이엔드타워2차', 'ADDRESS': '구로동 222-14', 'TELEPHONE': '6340-5555', 'APPROVAL_DATE': '2006.08.17', 'COMPLE_DATE': '2008.04.15'}, {'IDX': 186.0, 'FAC_NM': '아주디지털타워', 'ADDRESS': '성수동2가 284-56번지', 'TELEPHONE': '(02) 462-2235', 'APPROVAL_DATE': '2006.07.27', 'COMPLE_DATE': '2010.01.08'}, {'IDX': 213.0, 'FAC_NM': '산타플러스', 'ADDRESS': '난곡로 60', 'TELEPHONE': '02-865-6976', 'APPROVAL_DATE': '2005.11.28', 'COMPLE_DATE': '2006.7.26'}, {'IDX': 92.0, 'FAC_NM': '㈜동광인터내셔날', 'ADDRESS': '가산동 459-14', 'TELEPHONE': '3479-2700', 'APPROVAL_DATE': '2005.11.23', 'COMPLE_DATE': '2006.01'}, {'IDX': 152.0, 'FAC_NM': '월드메르디앙비즈센터', 'ADDRESS': '양산로 53(양평동3가)', 'TELEPHONE': '2165-8980', 'APPROVAL_DATE': '2005.10.05', 'COMPLE_DATE': '2007.02.14'}, {'IDX': 61.0, 'FAC_NM': '(주)한섬임대아파트형공장', 'ADDRESS': '가산동 60-42', 'TELEPHONE': '838-0146', 'APPROVAL_DATE': '2005.09.28', 'COMPLE_DATE': '2006.09'}, {'IDX': 41.0, 'FAC_NM': '㈜대양디앤티', 'ADDRESS': '구로동 197-47', 'TELEPHONE': '858-2111', 'APPROVAL_DATE': '2005.09.09', 'COMPLE_DATE': '2007.08.07'}, {'IDX': 91.0, 'FAC_NM': '승일벤쳐타워', 'ADDRESS': '가산동 371-42', 'TELEPHONE': '862-2351', 'APPROVAL_DATE': '2005.06.18', 'COMPLE_DATE': '2006.12'}, {'IDX': 42.0, 'FAC_NM': '대륭포스트타워3차', 'ADDRESS': '구로동 182-4', 'TELEPHONE': '2028-0114', 'APPROVAL_DATE': '2005.06.10', 'COMPLE_DATE': '2007.06.07'}, {'IDX': 153.0, 'FAC_NM': '에이스하이테크시티', 'ADDRESS': '경인로 775(문래동3가)', 'TELEPHONE': '6309-6112', 'APPROVAL_DATE': '2005.05.15', 'COMPLE_DATE': '2007.04.13'}, {'IDX': 90.0, 'FAC_NM': '롯데정보통신', 'ADDRESS': '가산동 533-2', 'TELEPHONE': '2626-4000', 'APPROVAL_DATE': '2005.05.11', 'COMPLE_DATE': '2007.03'}, {'IDX': 134.0, 'FAC_NM': 'DMC 첨단산업센터', 'ADDRESS': '마포구 상암동 1580 \n첨단산업센터', 'TELEPHONE': '2171-2847', 'APPROVAL_DATE': '2004.11.03', 'COMPLE_DATE': '2008.03.31'}, {'IDX': 62.0, 'FAC_NM': 'IT미래타워', 'ADDRESS': '가산동 60-21', 'TELEPHONE': '2027-5757', 'APPROVAL_DATE': '2004.10.27', 'COMPLE_DATE': '2007.04.30'}, {'IDX': 89.0, 'FAC_NM': '뉴티캐슬', 'ADDRESS': '가산동 429-1', 'TELEPHONE': '2626-9960', 'APPROVAL_DATE': '2004.08.11', 'COMPLE_DATE': '2006.12'}, {'IDX': 88.0, 'FAC_NM': '대륭테크노타운13차', 'ADDRESS': '가산동 664', 'TELEPHONE': '2029-5600', 'APPROVAL_DATE': '2004.07.28', 'COMPLE_DATE': '2008.05'}, {'IDX': 185.0, 'FAC_NM': '성수동\n 우림e-BIZ Center', 'ADDRESS': '성수동2가 280-21번지', 'TELEPHONE': '(02)2024-2110', 'APPROVAL_DATE': '2004.07.26', 'COMPLE_DATE': '2006.10.18'}, {'IDX': 132.0, 'FAC_NM': '중계제1공단', 'ADDRESS': '노원구 노원로19길 31(중계동)\n[중계동 511-2]', 'TELEPHONE': '948-2846', 'APPROVAL_DATE': '2004.07.13', 'COMPLE_DATE': '1991.12.07'}, {'IDX': 130.0, 'FAC_NM': '월계테크노타운', 'ADDRESS': '노원구 월계로45길 28(월계동)\n[월계동 562번지]', 'TELEPHONE': '990-2727', 'APPROVAL_DATE': '2004.07.08', 'COMPLE_DATE': '1994.12.19'}, {'IDX': 87.0, 'FAC_NM': '대륭테크노타운12차', 'ADDRESS': '가산동 327-32', 'TELEPHONE': '2029-6114', 'APPROVAL_DATE': '2004.07.08', 'COMPLE_DATE': '2008.05'}, {'IDX': 131.0, 'FAC_NM': '하계테크노타운', 'ADDRESS': '노원구 노원로15길 10(하계동)\n[하계동 250-3]', 'TELEPHONE': '6235-3500', 'APPROVAL_DATE': '2004.07.07', 'COMPLE_DATE': '1998.11.17'}, {'IDX': 184.0, 'FAC_NM': '풍림테크원', 'ADDRESS': '성수동2가 273-10번지', 'TELEPHONE': '(02) 468-9319/464-0133', 'APPROVAL_DATE': '2004.05.31', 'COMPLE_DATE': '2005.09.15'}, {'IDX': 31.0, 'FAC_NM': '이앤씨드림타워6차', 'ADDRESS': '구로동 197-28', 'TELEPHONE': '801-8603', 'APPROVAL_DATE': '2004.05.10', 'COMPLE_DATE': '2005.12.21'}, {'IDX': 39.0, 'FAC_NM': '대륭포스트타워2차', 'ADDRESS': '구로동 182-13', 'TELEPHONE': '2082-0114', 'APPROVAL_DATE': '2004.03.24', 'COMPLE_DATE': '2005.10.06'}, {'IDX': 60.0, 'FAC_NM': '스타밸리', 'ADDRESS': '가산동 60-11', 'TELEPHONE': '2027-0114', 'APPROVAL_DATE': '2004.02.27', 'COMPLE_DATE': '2006.04'}, {'IDX': 37.0, 'FAC_NM': '코오롱빌란트2차', 'ADDRESS': '구로동 222-8', 'TELEPHONE': '2081-1111', 'APPROVAL_DATE': '2004.02.25', 'COMPLE_DATE': '2006.12.28'}, {'IDX': 38.0, 'FAC_NM': '대륭포스트타워1차', 'ADDRESS': '구로동 212-8', 'TELEPHONE': '2082-2331', 'APPROVAL_DATE': '2004.01.10', 'COMPLE_DATE': '2005.10.18'}, {'IDX': 36.0, 'FAC_NM': '코오롱싸이언스밸리2차', 'ADDRESS': '구로동 811', 'TELEPHONE': '850-3150', 'APPROVAL_DATE': '2003.12.30', 'COMPLE_DATE': '2005.12.13'}, {'IDX': 34.0, 'FAC_NM': '에이스하이엔드1차', 'ADDRESS': '구로동 235-2', 'TELEPHONE': '6220-2010', 'APPROVAL_DATE': '2003.12.30', 'COMPLE_DATE': '2005.09.30'}, {'IDX': 150.0, 'FAC_NM': '메가벤처타워', 'ADDRESS': '문래로20길60(문래동3가)', 'TELEPHONE': '2632-4438', 'APPROVAL_DATE': '2003.12.22', 'COMPLE_DATE': '2005.12.27'}, {'IDX': 79.0, 'FAC_NM': '롯데IT캐슬', 'ADDRESS': '가산동 550-1', 'TELEPHONE': '2026-8970', 'APPROVAL_DATE': '2003.12.20', 'COMPLE_DATE': '2005.09'}, {'IDX': 30.0, 'FAC_NM': '이앤씨드림타워5차', 'ADDRESS': '구로동 197-13', 'TELEPHONE': '6336-3591', 'APPROVAL_DATE': '2003.12.19', 'COMPLE_DATE': '2004.12.14'}, {'IDX': 59.0, 'FAC_NM': '벽산디지털밸리5차', 'ADDRESS': '가산동 60-73', 'TELEPHONE': '2082-5990', 'APPROVAL_DATE': '2003.11.05', 'COMPLE_DATE': '2005.10'}, {'IDX': 33.0, 'FAC_NM': '마리오디지털밸리', 'ADDRESS': '구로동 222-12', 'TELEPHONE': '890-8498', 'APPROVAL_DATE': '2003.10.13', 'COMPLE_DATE': '2005.10.25'}, {'IDX': 85.0, 'FAC_NM': '코오롱디지털타워애스톤', 'ADDRESS': '가산동 505-14', 'TELEPHONE': '2082-8114', 'APPROVAL_DATE': '2003.09.26', 'COMPLE_DATE': '2005.09'}, {'IDX': 84.0, 'FAC_NM': '에이스테크노타워10차', 'ADDRESS': '가산동 470-5', 'TELEPHONE': '6670-5300', 'APPROVAL_DATE': '2003.09.16', 'COMPLE_DATE': '2005.07'}, {'IDX': 35.0, 'FAC_NM': '코오롱싸이언스밸리1차', 'ADDRESS': '구로동 187-10', 'TELEPHONE': '2025-4580', 'APPROVAL_DATE': '2003.08.08', 'COMPLE_DATE': '2005.07.05'}, {'IDX': 40.0, 'FAC_NM': '삼성IT밸리', 'ADDRESS': '구로동 197-5', 'TELEPHONE': '2028-2363', 'APPROVAL_DATE': '2003.07.20', 

,IDX,FAC_NM,ADDRESS,TELEPHONE,APPROVAL_DATE,COMPLE_DATE
0,208.0,신내테크노타운,봉화산로 123(상봉동),02)3423-0057,96.5.28,99.10.18
1,136.0,월곡동아파트형공장,하월곡동 96-113,02-090-8083,33289,1990.12.31
2,135.0,월곡동아파트형공장,하월곡동 96-113,02-912-1034,33289,1990.12.31
3,140.0,문정아르페온 1차 지식산업센터,서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL),031-706-8577,2016.06.27,2016.06.27
4,139.0,문정 대명벨리온,서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL),02-2222-7357,2016.03.23,2016.03.23
...,...,...,...,...,...,...
208,169.0,서울제일인쇄협동조합,성수2가제3동 277-7번지,(02) 498-8727,1992.02.06,1993.05.08
209,168.0,삼풍,성수2가제3동 284-50번지,(02) 466-4515,1991.01.31,1992.08.03
210,122.0,대동아파트형공장,독산동 999-3,804-3362,1990.12,1992.02
211,3.0,비젼타워관리조합,양천로57길26,2659-0360,1990.10.31,1992.11.30
212,142.0,문정 현대지식산업센터Ｉ-2,서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL),02-3451-0100,2016.02.29,2016.02.29

## 데이터 전처리

In [148]:
# 필요한 데이터만 추출하고, 열이름 모두 소문자로 통일
center_df = center_df[['IDX', 'FAC_NM', "ADDRESS"]]
center_df.columns = center_df.columns.str.lower()

center_df

       idx            fac_nm                                address
0    208.0           신내테크노타운                          봉화산로 123(상봉동)
1    136.0         월곡동아파트형공장                            하월곡동 96-113
2    135.0         월곡동아파트형공장                            하월곡동 96-113
3    140.0  문정아르페온 1차 지식산업센터    서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)
4    139.0          문정 대명벨리온  서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)
..     ...               ...                                    ...
208  169.0        서울제일인쇄협동조합                        성수2가제3동 277-7번지
209  168.0                삼풍                       성수2가제3동 284-50번지
210  122.0          대동아파트형공장                              독산동 999-3
211    3.0          비젼타워관리조합                               양천로57길26
212  142.0    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)

[213 rows x 3 columns]

In [149]:
# idx: float → int 로 변경
center_df['idx'] = center_df['idx'].astype(int)

# 값 중복 여부 확인
print(center_df['idx'].duplicated().sum()) # 0

0

In [150]:
# 공장 이름과 주소가 모두 같은 행이 있는지 확인
print(center_df.duplicated(subset=['fac_nm', 'address']).sum()) # 1

dup_all_mask = center_df.duplicated(subset=['fac_nm', 'address'], keep=False)
center_df[dup_all_mask].sort_values(['fac_nm', 'address'])

1

   idx     fac_nm      address
1  136  월곡동아파트형공장  하월곡동 96-113
2  135  월곡동아파트형공장  하월곡동 96-113

In [151]:
# 공장 이름과 주소 중복 행 제거
center_df = center_df.drop_duplicates(subset=['fac_nm', 'address'], keep='first').reset_index(drop=True)
center_df

     idx            fac_nm                                address
0    208           신내테크노타운                          봉화산로 123(상봉동)
1    136         월곡동아파트형공장                            하월곡동 96-113
2    140  문정아르페온 1차 지식산업센터    서울특별시 송파구 문정동 640\n(문정도시개발구역 5-1BL)
3    139          문정 대명벨리온  서울특별시 송파구 문정동 641-4\n(문정도시개발구역 4-3BL)
4    141    문정 현대지식산업센터Ｉ-1    서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)
..   ...               ...                                    ...
207  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지
208  168                삼풍                       성수2가제3동 284-50번지
209  122          대동아파트형공장                              독산동 999-3
210    3          비젼타워관리조합                               양천로57길26
211  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)

[212 rows x 3 columns]

In [152]:
# 주소 이상치 제거
center_df["address"] = (
    center_df["address"]
    .str.replace(r"(,|\n|외).*$", "", regex=True)  # 첫 , 또는 \n 또는 외 이후 전부 삭제
    .str.strip()
)

center_df

     idx            fac_nm                                address
0    208           신내테크노타운                          봉화산로 123(상봉동)
1    136         월곡동아파트형공장                            하월곡동 96-113
2    140  문정아르페온 1차 지식산업센터                      서울특별시 송파구 문정동 640
3    139          문정 대명벨리온                    서울특별시 송파구 문정동 641-4
4    141    문정 현대지식산업센터Ｉ-1    서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)
..   ...               ...                                    ...
207  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지
208  168                삼풍                       성수2가제3동 284-50번지
209  122          대동아파트형공장                              독산동 999-3
210    3          비젼타워관리조합                               양천로57길26
211  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)

[212 rows x 3 columns]

In [161]:
print(center_df['address'].str.contains(',').sum()) # 외 = 0, \n = 0, , = 1
print(center_df[center_df['address'].str.contains(',', na=False)]) # idx = 202

cond = center_df['idx'] == 202
center_df.loc[cond, 'address'] = '성수동2가 269-25' # 첫 주소로 대체

center_df.loc[cond, :]

1
    idx          fac_nm               address
19  202  에이스하이앤드\n 성수타워  성수동2가 269-25,269-51,

    idx          fac_nm       address
19  202  에이스하이앤드\n 성수타워  성수동2가 269-25

In [164]:
# type 변수 추가
center_df['type'] = '지식산업센터'
center_df

     idx            fac_nm                                address    type
0    208           신내테크노타운                          봉화산로 123(상봉동)  지식산업센터
1    136         월곡동아파트형공장                            하월곡동 96-113  지식산업센터
2    140  문정아르페온 1차 지식산업센터                      서울특별시 송파구 문정동 640  지식산업센터
3    139          문정 대명벨리온                    서울특별시 송파구 문정동 641-4  지식산업센터
4    141    문정 현대지식산업센터Ｉ-1    서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL)  지식산업센터
..   ...               ...                                    ...     ...
207  169        서울제일인쇄협동조합                        성수2가제3동 277-7번지  지식산업센터
208  168                삼풍                       성수2가제3동 284-50번지  지식산업센터
209  122          대동아파트형공장                              독산동 999-3  지식산업센터
210    3          비젼타워관리조합                               양천로57길26  지식산업센터
211  142    문정 현대지식산업센터Ｉ-2  서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL)  지식산업센터

[212 rows x 4 columns]

### 주소 → 위도, 경도

In [143]:
kakao_key  = os.getenv("KAKAO_REST_APIKEY")     # 인증키

In [163]:
# test
url = "	https://dapi.kakao.com/v2/local/search/address.json" #요청할 url 주소
headers = {"Authorization": f"KakaoAK {kakao_key}"} #REST API 키(유효한 키)
params = {"query": "성수동2가 269-25"}  # 입력할 주소
resp = requests.get(url,headers=headers, params=params).json() #카카오 API 요청
                      
print(resp) #API 결과 출력
resp['documents'][0]['road_address']

{'documents': [{'address': {'address_name': '서울 성동구 성수동2가 269-25', 'b_code': '1120011500', 'h_code': '1120067000', 'main_address_no': '269', 'mountain_yn': 'N', 'region_1depth_name': '서울', 'region_2depth_name': '성동구', 'region_3depth_h_name': '성수2가1동', 'region_3depth_name': '성수동2가', 'sub_address_no': '25', 'x': '127.056741837461', 'y': '37.5402196364231'}, 'address_name': '서울 성동구 성수동2가 269-25', 'address_type': 'REGION_ADDR', 'road_address': {'address_name': '서울 성동구 성수이로10길 14', 'building_name': '에이스 하이엔드 성수타워', 'main_building_no': '14', 'region_1depth_name': '서울', 'region_2depth_name': '성동구', 'region_3depth_name': '성수동2가', 'road_name': '성수이로10길', 'sub_building_no': '', 'underground_yn': 'N', 'x': '127.056789858953', 'y': '37.5401307747523', 'zone_no': '04784'}, 'x': '127.056741837461', 'y': '37.5402196364231'}], 'meta': {'is_end': True, 'pageable_count': 1, 'total_count': 1}}

{'address_name': '서울 성동구 성수이로10길 14',
 'building_name': '에이스 하이엔드 성수타워',
 'main_building_no': '14',
 'region_1depth_name': '서울',
 'region_2depth_name': '성동구',
 'region_3depth_name': '성수동2가',
 'road_name': '성수이로10길',
 'sub_building_no': '',
 'underground_yn': 'N',
 'x': '127.056789858953',
 'y': '37.5401307747523',
 'zone_no': '04784'}

In [165]:
url = "	https://dapi.kakao.com/v2/local/search/address.json" #요청할 url 주소
headers = {"Authorization": f"KakaoAK {kakao_key}"} #REST API 키(유효한 키)

for idx, add in center_df['address'].items():
    params = {"query": add}
    resp = requests.get(url, headers=headers, params=params).json()

    docs = resp.get('documents', [])
    if not docs:
        continue

    road = docs[0].get('road_address')  # 없을 수도 있음

    if road:
        center_df.loc[idx, 'road_address'] = road.get('address_name')
        center_df.loc[idx, 'lat'] = road.get('y') # Y 좌표값, 경위도인 경우 위도(latitude)
        center_df.loc[idx, 'lng'] = road.get('x') # X 좌표값, 경위도인 경우 경도(longitude)
    else:
        # road_address가 없으면 지번주소(address) 기준으로라도 좌표 저장
        addr = docs[0].get('address')
        if addr:
            center_df.loc[idx, 'road_address'] = addr.get('address_name')
            center_df.loc[idx, 'lat'] = addr.get('y')
            center_df.loc[idx, 'lng'] = addr.get('x')

center_df

,idx,fac_nm,address,type,road_address,lat,lng
0,208,신내테크노타운,봉화산로 123(상봉동),지식산업센터,서울 중랑구 봉화산로 123,37.6040273751759,127.087795907582
1,136,월곡동아파트형공장,하월곡동 96-113,지식산업센터,서울 성북구 오패산로 21,37.6041194415259,127.037068364923
2,140,문정아르페온 1차 지식산업센터,서울특별시 송파구 문정동 640,지식산업센터,서울 송파구 정의로 70,37.486047580834,127.115467768303
3,139,문정 대명벨리온,서울특별시 송파구 문정동 641-4,지식산업센터,서울 송파구 법원로 127,37.4863159476467,127.118783475412
4,141,문정 현대지식산업센터Ｉ-1,서울특별시 송파구 문정동 644 (문정 특별계획구역 6-1BL),지식산업센터,서울 송파구 법원로11길 11,37.4846302643031,127.118322322397
...,...,...,...,...,...,...,...
207,169,서울제일인쇄협동조합,성수2가제3동 277-7번지,지식산업센터,서울 성동구 성수이로 144-29,37.5477016713796,127.059035636627
208,168,삼풍,성수2가제3동 284-50번지,지식산업센터,서울 성동구 성수일로10길 8,37.5477102587413,127.051466260849
209,122,대동아파트형공장,독산동 999-3,지식산업센터,서울 금천구 범안로9길 58,37.468804929751,126.889870514728
210,3,비젼타워관리조합,양천로57길26,지식산업센터,서울 강서구 양천로57길 26,37.5637547781595,126.853091955234
211,142,문정 현대지식산업센터Ｉ-2,서울특별시 송파구 문정동 644-2 (문정 특별계획구역 6-2BL),지식산업센터,서울 송파구 법원로11길 7,37.4852991782959,127.119391411935

In [166]:
print(center_df['road_address'].str.contains('서울').sum())

not_seoul = center_df[~center_df['road_address'].str.contains('서울')]
not_seoul

210

     idx      fac_nm      address    type road_address  lat  lng
152   77  우림라이온스밸리1차   가산동 371-62  지식산업센터          NaN  NaN  NaN
194   48          천강  신도림동 402-3호  지식산업센터          NaN  NaN  NaN

In [168]:
'''
77	우림라이온스밸리1차	가산동 371-62
48	천강	신도림동 402-3호
두 주소는 이상치로 보고 제거.
'''
center_df.dropna(inplace=True)
len(center_df)

210

In [169]:
# idx 재설정 및 정렬
center_df.sort_values(by = 'idx', inplace=True)
center_df['idx'] = range(1, len(center_df) + 1) # idx 번호 재부여
center_df.reset_index(drop=True, inplace=True) # index 재설정
center_df

,idx,fac_nm,address,type,road_address,lat,lng
0,1,세종투자㈜,강동구 상일로10길 36 (상일동),지식산업센터,서울 강동구 상일로10길 36,37.5507989598659,127.174104292142
1,2,NICE그룹 지식산업센터,상일로6길 55 (상일동),지식산업센터,서울 강동구 상일로6길 55,37.5500039560221,127.176326474473
2,3,비젼타워관리조합,양천로57길26,지식산업센터,서울 강서구 양천로57길 26,37.5637547781595,126.853091955234
3,4,에이스테크노타워,강서로 468,지식산업센터,서울 강서구 강서로 468,37.5671848166792,126.841489818891
4,5,가양테크노타운,허준로 217,지식산업센터,서울 강서구 허준로 217,37.5609643758115,126.862889794292
...,...,...,...,...,...,...,...
205,206,강북전자공단,강북구 덕릉로40길 74(번동,지식산업센터,서울 강북구 덕릉로40길 74,37.634162368067,127.033671249468
206,207,강북유니온빌딩,강북구 한천로109길 10(번동,지식산업센터,서울 강북구 한천로109길 10,37.6288059246607,127.043312515269
207,208,아시아미디어타워,초동 42,지식산업센터,서울 중구 충무로 29,37.563836750265,126.992508328619
208,209,동대문패션비즈센터,신당동 251-160,지식산업센터,서울 중구 을지로45길 46,37.5663548952676,127.012362709547
209,210,산타플러스,난곡로 60,지식산업센터,서울 관악구 난곡로 60,37.4608681432511,126.919395468118

# csv로 내보내기

In [170]:
center_df.to_csv("center_df.csv", index=False, encoding="utf-8-sig")