In [1]:
import pandas as pd
import re

# 서울시 버스정류소 위치정보

## 1. 데이터 불러오기 및 확인

In [5]:
df_raw = pd.read_csv(
    "/Users/danha/Desktop/IT/project/team_project_brew_map/git/data/서울시 버스정류소 위치정보 (1).csv",
    encoding="cp949"
)

print("Shape:", df_raw.shape)
print("Columns:", df_raw.columns.tolist())
df_raw.head()

Shape: (11237, 6)
Columns: ['노드 ID', '정류소번호', '정류소명', 'X좌표', 'Y좌표', '정류소 타입']

       노드 ID  정류소번호   정류소명         X좌표        Y좌표 정류소 타입
0  110000669  11833    중계역  127.062765  37.647269  가로변시간
1  110000663  11834    중계역  127.062845  37.648085  가로변시간
2  110000661  11835    하계역  127.068859  37.635040  가로변시간
3  110000662  11836    하계역  127.068347  37.635156  가로변시간
4  110900053  11842  선곡경로당  127.058661  37.617081   마을버스

In [6]:
print('=== 데이터 타입 ===')
print(df_raw.dtypes)

print('=== 결측값 현황 ===')
print(df_raw.isnull().sum())

=== 데이터 타입 ===
노드 ID       int64
정류소번호       int64
정류소명       object
X좌표       float64
Y좌표       float64
정류소 타입     object
dtype: object
=== 결측값 현황 ===
노드 ID     0
정류소번호     0
정류소명      0
X좌표       0
Y좌표       0
정류소 타입    0
dtype: int64

## 2. 핵심 데이터 추출

In [ ]:
clean_cols = ['정류소번호', '정류소명', 'X좌표', 'Y좌표']
df_raw = df_raw[clean_cols]

print(f'추출 후 Shape: {df_raw.shape}')
df_raw.head()

추출 후 Shape: (11237, 4)

   정류소번호   정류소명         X좌표        Y좌표
0  11833    중계역  127.062765  37.647269
1  11834    중계역  127.062845  37.648085
2  11835    하계역  127.068859  37.635040
3  11836    하계역  127.068347  37.635156
4  11842  선곡경로당  127.058661  37.617081

## 3. 열이름 영소문자 구분

In [18]:
col_rename = {
    '정류소번호' : 'bus_stop_id',
    '정류소명'    : 'bus_stop_nm',
    'X좌표'     : 'lng',
    'Y좌표': 'lat'
}
df_raw = df_raw.rename(columns=col_rename)
print('변환된 컬럼명:', df_raw.columns.tolist())
df_raw.head()

변환된 컬럼명: ['bus_stop_id', 'bus_stop_nm', 'lng', 'lat']

   bus_stop_id bus_stop_nm         lng        lat
0        11833         중계역  127.062765  37.647269
1        11834         중계역  127.062845  37.648085
2        11835         하계역  127.068859  37.635040
3        11836         하계역  127.068347  37.635156
4        11842       선곡경로당  127.058661  37.617081

## 4. type 행 추가

In [19]:
df_raw['type'] = '버스정류장'
df_raw.head()

   bus_stop_id bus_stop_nm         lng        lat   type
0        11833         중계역  127.062765  37.647269  버스정류장
1        11834         중계역  127.062845  37.648085  버스정류장
2        11835         하계역  127.068859  37.635040  버스정류장
3        11836         하계역  127.068347  37.635156  버스정류장
4        11842       선곡경로당  127.058661  37.617081  버스정류장

In [23]:
save_path = "/Users/danha/Desktop/IT/project/team_project_brew_map/git/data/bus_stop.csv"

df_raw.to_csv(save_path, index=False, encoding="utf-8-sig")

print("저장 완료:", save_path)

저장 완료: /Users/danha/Desktop/IT/project/team_project_brew_map/git/data/bus_stop.csv